#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using Excelsior.Domain;

namespace Excelsior.Domain	
{
	public partial class Aspnet_User
	{
		private string _UserName;
		public virtual string UserName
		{
			get
			{
				return this._UserName;
			}
			set
			{
				this._UserName = value;
			}
		}
		
		private Guid _UserId;
		public virtual Guid UserId
		{
			get
			{
				return this._UserId;
			}
			set
			{
				this._UserId = value;
			}
		}
		
		private string _MobileAlias;
		public virtual string MobileAlias
		{
			get
			{
				return this._MobileAlias;
			}
			set
			{
				this._MobileAlias = value;
			}
		}
		
		private string _LoweredUserName;
		public virtual string LoweredUserName
		{
			get
			{
				return this._LoweredUserName;
			}
			set
			{
				this._LoweredUserName = value;
			}
		}
		
		private DateTime _LastActivityDate;
		public virtual DateTime LastActivityDate
		{
			get
			{
				return this._LastActivityDate;
			}
			set
			{
				this._LastActivityDate = value;
			}
		}
		
		private bool _IsAnonymous;
		public virtual bool IsAnonymous
		{
			get
			{
				return this._IsAnonymous;
			}
			set
			{
				this._IsAnonymous = value;
			}
		}
		
		private Guid _ApplicationId;
		public virtual Guid ApplicationId
		{
			get
			{
				return this._ApplicationId;
			}
			set
			{
				this._ApplicationId = value;
			}
		}
		
		private Aspnet_Application _AspnetApplication;
		public virtual Aspnet_Application AspnetApplication
		{
			get
			{
				return this._AspnetApplication;
			}
			set
			{
				this._AspnetApplication = value;
			}
		}
		
		private IList<CONTACT_User> _CONTACTUsers = new List<CONTACT_User>();
		public virtual IList<CONTACT_User> CONTACT_Users
		{
			get
			{
				return this._CONTACTUsers;
			}
		}

        private IList<AUTH_Client> _AUTHClients = new List<AUTH_Client>();
        public virtual IList<AUTH_Client> AUTH_Clients
        {
            get
            {
                return this._AUTHClients;
            }
        }
    }
}
#pragma warning restore 1591
