#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using Excelsior.Domain;

namespace Excelsior.Domain	
{
	public partial class Aspnet_Membership : Aspnet_User
	{
		private string _PasswordSalt;
		public virtual string PasswordSalt
		{
			get
			{
				return this._PasswordSalt;
			}
			set
			{
				this._PasswordSalt = value;
			}
		}
		
		private string _PasswordQuestion;
		public virtual string PasswordQuestion
		{
			get
			{
				return this._PasswordQuestion;
			}
			set
			{
				this._PasswordQuestion = value;
			}
		}
		
		private int _PasswordFormat;
		public virtual int PasswordFormat
		{
			get
			{
				return this._PasswordFormat;
			}
			set
			{
				this._PasswordFormat = value;
			}
		}
		
		private string _PasswordAnswer;
		public virtual string PasswordAnswer
		{
			get
			{
				return this._PasswordAnswer;
			}
			set
			{
				this._PasswordAnswer = value;
			}
		}
		
		private string _Password;
		public virtual string Password
		{
			get
			{
				return this._Password;
			}
			set
			{
				this._Password = value;
			}
		}
		
		private string _MobilePIN;
		public virtual string MobilePIN
		{
			get
			{
				return this._MobilePIN;
			}
			set
			{
				this._MobilePIN = value;
			}
		}
		
		private string _LoweredEmail;
		public virtual string LoweredEmail
		{
			get
			{
				return this._LoweredEmail;
			}
			set
			{
				this._LoweredEmail = value;
			}
		}
		
		private DateTime _LastPasswordChangedDate;
		public virtual DateTime LastPasswordChangedDate
		{
			get
			{
				return this._LastPasswordChangedDate;
			}
			set
			{
				this._LastPasswordChangedDate = value;
			}
		}
		
		private DateTime _LastLoginDate;
		public virtual DateTime LastLoginDate
		{
			get
			{
				return this._LastLoginDate;
			}
			set
			{
				this._LastLoginDate = value;
			}
		}
		
		private DateTime _LastLockoutDate;
		public virtual DateTime LastLockoutDate
		{
			get
			{
				return this._LastLockoutDate;
			}
			set
			{
				this._LastLockoutDate = value;
			}
		}
		
		private bool _IsLockedOut;
		public virtual bool IsLockedOut
		{
			get
			{
				return this._IsLockedOut;
			}
			set
			{
				this._IsLockedOut = value;
			}
		}
		
		private bool _IsApproved;
		public virtual bool IsApproved
		{
			get
			{
				return this._IsApproved;
			}
			set
			{
				this._IsApproved = value;
			}
		}
		
		private DateTime _FailedPasswordAttemptWindowStart;
		public virtual DateTime FailedPasswordAttemptWindowStart
		{
			get
			{
				return this._FailedPasswordAttemptWindowStart;
			}
			set
			{
				this._FailedPasswordAttemptWindowStart = value;
			}
		}
		
		private int _FailedPasswordAttemptCount;
		public virtual int FailedPasswordAttemptCount
		{
			get
			{
				return this._FailedPasswordAttemptCount;
			}
			set
			{
				this._FailedPasswordAttemptCount = value;
			}
		}
		
		private DateTime _FailedPasswordAnswerAttemptWindowStart;
		public virtual DateTime FailedPasswordAnswerAttemptWindowStart
		{
			get
			{
				return this._FailedPasswordAnswerAttemptWindowStart;
			}
			set
			{
				this._FailedPasswordAnswerAttemptWindowStart = value;
			}
		}
		
		private int _FailedPasswordAnswerAttemptCount;
		public virtual int FailedPasswordAnswerAttemptCount
		{
			get
			{
				return this._FailedPasswordAnswerAttemptCount;
			}
			set
			{
				this._FailedPasswordAnswerAttemptCount = value;
			}
		}
		
		private string _Email;
		public virtual string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				this._Email = value;
			}
		}
		
		private DateTime _CreateDate;
		public virtual DateTime CreateDate
		{
			get
			{
				return this._CreateDate;
			}
			set
			{
				this._CreateDate = value;
			}
		}
		
		private string _Comment;
		public virtual string Comment
		{
			get
			{
				return this._Comment;
			}
			set
			{
				this._Comment = value;
			}
		}
		
		private Guid _ApplicationId;
		public override Guid ApplicationId
		{
			get
			{
				return this._ApplicationId;
			}
			set
			{
				this._ApplicationId = value;
                base.ApplicationId = value;
			}
        }
        private Aspnet_Application _AspnetApplication;
        public override Aspnet_Application AspnetApplication
        {
            get
            {
                return this._AspnetApplication;
            }
            set
            {
                this._AspnetApplication = value;
                base.AspnetApplication = value;
            }
        }
    }
}
#pragma warning restore 1591
