#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using Excelsior.Domain;

namespace Excelsior.Domain	
{
	public partial class AUDIT_Record
	{
		private long _AuditRecordID;
		public virtual long AuditRecordID
		{
			get
			{
				return this._AuditRecordID;
			}
			set
			{
				this._AuditRecordID = value;
			}
		}
		
		private long? _UserID;
		public virtual long? UserID
		{
			get
			{
				return this._UserID;
			}
			set
			{
				this._UserID = value;
			}
		}
		
		private DateTime? _PerformedDateTime;
		public virtual DateTime? PerformedDateTime
		{
			get
			{
				return this._PerformedDateTime;
			}
			set
			{
				this._PerformedDateTime = value;
			}
		}
		
		private long? _AuditActionID;
		public virtual long? AuditActionID
		{
			get
			{
				return this._AuditActionID;
			}
			set
			{
				this._AuditActionID = value;
			}
		}
		
		private long? _TrialID;
		public virtual long? TrialID
		{
			get
			{
				return this._TrialID;
			}
			set
			{
				this._TrialID = value;
			}
		}
		
		private long? _SeriesID;
		public virtual long? SeriesID
		{
			get
			{
				return this._SeriesID;
			}
			set
			{
				this._SeriesID = value;
			}
		}
		
		private long? _WFTempStepID;
		public virtual long? WFTempStepID
		{
			get
			{
				return this._WFTempStepID;
			}
			set
			{
				this._WFTempStepID = value;
			}
		}
		
		private long? _CertUploadInfoID;
		public virtual long? CertUploadInfoID
		{
			get
			{
				return this._CertUploadInfoID;
			}
			set
			{
				this._CertUploadInfoID = value;
			}
		}
		
		private string _ReasonForChange;
		public virtual string ReasonForChange
		{
			get
			{
				return this._ReasonForChange;
			}
			set
			{
				this._ReasonForChange = value;
			}
		}
		
		private long? _CertUserID;
		public virtual long? CertUserID
		{
			get
			{
				return this._CertUserID;
			}
			set
			{
				this._CertUserID = value;
			}
		}
		
		private long? _CertEquipmentID;
		public virtual long? CertEquipmentID
		{
			get
			{
				return this._CertEquipmentID;
			}
			set
			{
				this._CertEquipmentID = value;
			}
		}
		
		private string _SoftwareVersion;
		public virtual string SoftwareVersion
		{
			get
			{
				return this._SoftwareVersion;
			}
			set
			{
				this._SoftwareVersion = value;
			}
		}
		
		private long? _SubjectID;
		public virtual long? SubjectID
		{
			get
			{
				return this._SubjectID;
			}
			set
			{
				this._SubjectID = value;
			}
		}
		
		private long? _RelatedUserID;
		public virtual long? RelatedUserID
		{
			get
			{
				return this._RelatedUserID;
			}
			set
			{
				this._RelatedUserID = value;
			}
		}

        private string _DetailsXML;
        public virtual string DetailsXML
        {
            get
            {
                return this._DetailsXML;
            }
            set
            {
                this._DetailsXML = value;
            }
        }

        private WF_TempStep _WFTempStep;
		public virtual WF_TempStep WFTempStep
		{
			get
			{
				return this._WFTempStep;
			}
			set
			{
				this._WFTempStep = value;
			}
		}
		
		private PACS_Trial _PACSTrial;
		public virtual PACS_Trial PACSTrial
		{
			get
			{
				return this._PACSTrial;
			}
			set
			{
				this._PACSTrial = value;
			}
		}
		
		private PACS_Series _PACSSeries;
		public virtual PACS_Series PACSSeries
		{
			get
			{
				return this._PACSSeries;
			}
			set
			{
				this._PACSSeries = value;
			}
		}
		
		private CONTACT_User _CONTACTUser;
		public virtual CONTACT_User CONTACTUser
		{
			get
			{
				return this._CONTACTUser;
			}
			set
			{
				this._CONTACTUser = value;
			}
		}
		
		private CERT_UploadInfo _CERTUploadInfo;
		public virtual CERT_UploadInfo CERTUploadInfo
		{
			get
			{
				return this._CERTUploadInfo;
			}
			set
			{
				this._CERTUploadInfo = value;
			}
		}
		
		private AUDIT_Action _AUDITAction;
		public virtual AUDIT_Action AUDITAction
		{
			get
			{
				return this._AUDITAction;
			}
			set
			{
				this._AUDITAction = value;
			}
		}
		
		private CERT_User _CERTUser;
		public virtual CERT_User CERTUser
		{
			get
			{
				return this._CERTUser;
			}
			set
			{
				this._CERTUser = value;
			}
		}
		
		private CERT_Equipment _CERTEquipment;
		public virtual CERT_Equipment CERTEquipment
		{
			get
			{
				return this._CERTEquipment;
			}
			set
			{
				this._CERTEquipment = value;
			}
		}
		
		private PACS_Subject _PACSSubject;
		public virtual PACS_Subject PACSSubject
		{
			get
			{
				return this._PACSSubject;
			}
			set
			{
				this._PACSSubject = value;
			}
		}
		
		private CONTACT_User _RelatedUser;
		public virtual CONTACT_User RelatedUser
		{
			get
			{
				return this._RelatedUser;
			}
			set
			{
				this._RelatedUser = value;
			}
		}
		
	}
}
#pragma warning restore 1591
