#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using Excelsior.Domain;

namespace Excelsior.Domain	
{
	public partial class AUDIT_CRUDAudit
	{
		private long _AuditID;
		public virtual long AuditID
		{
			get
			{
				return this._AuditID;
			}
			set
			{
				this._AuditID = value;
			}
		}
		
		private string _ObjectID;
		public virtual string ObjectID
		{
			get
			{
				return this._ObjectID;
			}
			set
			{
				this._ObjectID = value;
			}
		}
		
		private string _Type;
		public virtual string Type
		{
			get
			{
				return this._Type;
			}
			set
			{
				this._Type = value;
			}
		}
		
		private string _ClassName;
		public virtual string ClassName
		{
			get
			{
				return this._ClassName;
			}
			set
			{
				this._ClassName = value;
			}
		}
		
		private string _TableName;
		public virtual string TableName
		{
			get
			{
				return this._TableName;
			}
			set
			{
				this._TableName = value;
			}
		}
		
		private long? _RowID;
		public virtual long? RowID
		{
			get
			{
				return this._RowID;
			}
			set
			{
				this._RowID = value;
			}
		}
		
		private string _OldData;
		public virtual string OldData
		{
			get
			{
				return this._OldData;
			}
			set
			{
				this._OldData = value;
			}
		}
		
		private string _NewData;
		public virtual string NewData
		{
			get
			{
				return this._NewData;
			}
			set
			{
				this._NewData = value;
			}
		}
		
		private DateTime? _AuditDate;
		public virtual DateTime? AuditDate
		{
			get
			{
				return this._AuditDate;
			}
			set
			{
				this._AuditDate = value;
			}
		}
		
		private long? _UserID;
		public virtual long? UserID
		{
			get
			{
				return this._UserID;
			}
			set
			{
				this._UserID = value;
			}
		}
		
		private CONTACT_User _CONTACTUser;
		public virtual CONTACT_User CONTACTUser
		{
			get
			{
				return this._CONTACTUser;
			}
			set
			{
				this._CONTACTUser = value;
			}
		}
		
	}
}
#pragma warning restore 1591
