#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using Excelsior.Domain;

namespace Excelsior.Domain	
{
	public partial class BGD_Job
	{
		private long _JobID;
		public virtual long JobID
		{
			get
			{
				return this._JobID;
			}
			set
			{
				this._JobID = value;
			}
		}
		
		private string _JobType;
		public virtual string JobType
		{
			get
			{
				return this._JobType;
			}
			set
			{
				this._JobType = value;
			}
		}
		
		private string _Parameters;
		public virtual string Parameters
		{
			get
			{
				return this._Parameters;
			}
			set
			{
				this._Parameters = value;
			}
		}
		
		private int? _JobStatusID;
		public virtual int? JobStatusID
		{
			get
			{
				return this._JobStatusID;
			}
			set
			{
				this._JobStatusID = value;
			}
		}
		
		private int? _ProgressValue;
		public virtual int? ProgressValue
		{
			get
			{
				return this._ProgressValue;
			}
			set
			{
				this._ProgressValue = value;
			}
		}
		
		private bool _HasError;
		public virtual bool HasError
		{
			get
			{
				return this._HasError;
			}
			set
			{
				this._HasError = value;
			}
		}
		
		private string _LastError;
		public virtual string LastError
		{
			get
			{
				return this._LastError;
			}
			set
			{
				this._LastError = value;
			}
		}
		
		private long? _UserID;
		public virtual long? UserID
		{
			get
			{
				return this._UserID;
			}
			set
			{
				this._UserID = value;
			}
		}
		
		private DateTime? _CreatedDate;
		public virtual DateTime? CreatedDate
		{
			get
			{
				return this._CreatedDate;
			}
			set
			{
				this._CreatedDate = value;
			}
		}
		
		private string _ResultLocation;
		public virtual string ResultLocation
		{
			get
			{
				return this._ResultLocation;
			}
			set
			{
				this._ResultLocation = value;
			}
		}
		
		private long? _TrialID;
		public virtual long? TrialID
		{
			get
			{
				return this._TrialID;
			}
			set
			{
				this._TrialID = value;
			}
		}
		
		private bool _IsDismissed;
		public virtual bool IsDismissed
		{
			get
			{
				return this._IsDismissed;
			}
			set
			{
				this._IsDismissed = value;
			}
		}
		
		private BGD_JobStatus _BGDJobStatus;
		public virtual BGD_JobStatus BGDJobStatus
		{
			get
			{
				return this._BGDJobStatus;
			}
			set
			{
				this._BGDJobStatus = value;
			}
		}
		
		private CONTACT_User _CONTACTUser;
		public virtual CONTACT_User CONTACTUser
		{
			get
			{
				return this._CONTACTUser;
			}
			set
			{
				this._CONTACTUser = value;
			}
		}
		
		private PACS_Trial _PACSTrial;
		public virtual PACS_Trial PACSTrial
		{
			get
			{
				return this._PACSTrial;
			}
			set
			{
				this._PACSTrial = value;
			}
		}
		
	}
}
#pragma warning restore 1591
