#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using Excelsior.Domain;

namespace Excelsior.Domain	
{
	public partial class CERT_QuestionList
	{
		private long _CertQuestionListID;
		public virtual long CertQuestionListID
		{
			get
			{
				return this._CertQuestionListID;
			}
			set
			{
				this._CertQuestionListID = value;
			}
		}
		
		private long? _ImgProcedureID;
		public virtual long? ImgProcedureID
		{
			get
			{
				return this._ImgProcedureID;
			}
			set
			{
				this._ImgProcedureID = value;
			}
		}
		
		private string _CertQuestionDes;
		public virtual string CertQuestionDes
		{
			get
			{
				return this._CertQuestionDes;
			}
			set
			{
				this._CertQuestionDes = value;
			}
		}
		
		private CERT_ImgProcedureList _CERTImgProcedureList;
		public virtual CERT_ImgProcedureList CERTImgProcedureList
		{
			get
			{
				return this._CERTImgProcedureList;
			}
			set
			{
				this._CERTImgProcedureList = value;
			}
		}
		
		private IList<CERT_Result> _CERTResults = new List<CERT_Result>();
		public virtual IList<CERT_Result> CERT_Results
		{
			get
			{
				return this._CERTResults;
			}
		}
		
	}
}
#pragma warning restore 1591
