#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using Excelsior.Domain;

namespace Excelsior.Domain	
{
	public partial class CERT_Equipment
	{
		private long? _TrialID;
		public virtual long? TrialID
		{
			get
			{
				return this._TrialID;
			}
			set
			{
				this._TrialID = value;
			}
		}
		
		private long? _ImgProcedureID;
		public virtual long? ImgProcedureID
		{
			get
			{
				return this._ImgProcedureID;
			}
			set
			{
				this._ImgProcedureID = value;
			}
		}
		
		private long? _EquipmentID;
		public virtual long? EquipmentID
		{
			get
			{
				return this._EquipmentID;
			}
			set
			{
				this._EquipmentID = value;
			}
		}

        private DateTime? _DateCreated;
        public virtual DateTime? DateCreated
        {
            get
            {
                return this._DateCreated;
            }
            set
            {
                this._DateCreated = value;
            }
        }

        private DateTime? _DateofCertification;
		public virtual DateTime? DateofCertification
		{
			get
			{
				return this._DateofCertification;
			}
			set
			{
				this._DateofCertification = value;
			}
		}
		
		private bool _IsCertified;
		public virtual bool IsCertified
		{
			get
			{
				return this._IsCertified;
			}
			set
			{
				this._IsCertified = value;
			}
		}
		
		private long _CertEquipmentID;
		public virtual long CertEquipmentID
		{
			get
			{
				return this._CertEquipmentID;
			}
			set
			{
				this._CertEquipmentID = value;
			}
		}
		
		private double? _PixelSpacingY;
		public virtual double? PixelSpacingY
		{
			get
			{
				return this._PixelSpacingY;
			}
			set
			{
				this._PixelSpacingY = value;
			}
		}
		
		private double? _PixelSpacingX;
		public virtual double? PixelSpacingX
		{
			get
			{
				return this._PixelSpacingX;
			}
			set
			{
				this._PixelSpacingX = value;
			}
		}
		
		private double? _FrameSpacing;
		public virtual double? FrameSpacing
		{
			get
			{
				return this._FrameSpacing;
			}
			set
			{
				this._FrameSpacing = value;
			}
		}
		
		private bool _IsActive;
		public virtual bool IsActive
		{
			get
			{
				return this._IsActive;
			}
			set
			{
				this._IsActive = value;
			}
		}

        private long? _AssignedToID;
        public virtual long? AssignedToID
        {
            get
            {
                return this._AssignedToID;
            }
            set
            {
                this._AssignedToID = value;
            }
        }

        private long? _CertifiedByID;
		public virtual long? CertifiedByID
		{
			get
			{
				return this._CertifiedByID;
			}
			set
			{
				this._CertifiedByID = value;
			}
		}
		
		private PACS_Trial _PACSTrial;
		public virtual PACS_Trial PACSTrial
		{
			get
			{
				return this._PACSTrial;
			}
			set
			{
				this._PACSTrial = value;
			}
		}
		
		private CERT_ImgProcedureList _CERTImgProcedureList;
		public virtual CERT_ImgProcedureList CERTImgProcedureList
		{
			get
			{
				return this._CERTImgProcedureList;
			}
			set
			{
				this._CERTImgProcedureList = value;
			}
		}
		
		private CONTACT_Equipment _CONTACTEquipment;
		public virtual CONTACT_Equipment CONTACTEquipment
		{
			get
			{
				return this._CONTACTEquipment;
			}
			set
			{
				this._CONTACTEquipment = value;
			}
		}

        private CONTACT_User _AssignedTo;
        public virtual CONTACT_User AssignedTo
        {
            get
            {
                return this._AssignedTo;
            }
            set
            {
                this._AssignedTo = value;
            }
        }

        private CONTACT_User _CertifiedBy;
		public virtual CONTACT_User CertifiedBy
		{
			get
			{
				return this._CertifiedBy;
			}
			set
			{
				this._CertifiedBy = value;
			}
		}
		
		private IList<CERT_UploadInfo> _CERTUploadInfos = new List<CERT_UploadInfo>();
		public virtual IList<CERT_UploadInfo> CERT_UploadInfos
		{
			get
			{
				return this._CERTUploadInfos;
			}
		}
		
		private IList<QRY_Query> _QRYQueries = new List<QRY_Query>();
		public virtual IList<QRY_Query> QRY_Queries
		{
			get
			{
				return this._QRYQueries;
			}
		}
		
		//private IList<AUDIT_Record> _AUDITRecords = new List<AUDIT_Record>();
		//public virtual IList<AUDIT_Record> AUDIT_Records
		//{
		//	get
		//	{
		//		return this._AUDITRecords;
		//	}
		//}

        private IList<PACS_RawDatum> _PACSRawData = new List<PACS_RawDatum>();
        public virtual IList<PACS_RawDatum> PACS_RawData
        {
            get
            {
                return this._PACSRawData;
            }
        }
    }
}
#pragma warning restore 1591
