#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using Excelsior.Domain;

namespace Excelsior.Domain	
{
	public partial class CERT_UploadInfo
	{
		private long _CertUploadInfoID;
		public virtual long CertUploadInfoID
		{
			get
			{
				return this._CertUploadInfoID;
			}
			set
			{
				this._CertUploadInfoID = value;
			}
		}
		
		private long? _QueryID;
		public virtual long? QueryID
		{
			get
			{
				return this._QueryID;
			}
			set
			{
				this._QueryID = value;
			}
		}
		
		private long? _CertUserID;
		public virtual long? CertUserID
		{
			get
			{
				return this._CertUserID;
			}
			set
			{
				this._CertUserID = value;
			}
		}
		
		private long? _CertEquipmentID;
		public virtual long? CertEquipmentID
		{
			get
			{
				return this._CertEquipmentID;
			}
			set
			{
				this._CertEquipmentID = value;
			}
		}
		
		private bool _IsCertified;
		public virtual bool IsCertified
		{
			get
			{
				return this._IsCertified;
			}
			set
			{
				this._IsCertified = value;
			}
		}
		
		private DateTime? _PhotoDate;
		public virtual DateTime? PhotoDate
		{
			get
			{
				return this._PhotoDate;
			}
			set
			{
				this._PhotoDate = value;
			}
		}
		
		private DateTime? _UploadDate;
		public virtual DateTime? UploadDate
		{
			get
			{
				return this._UploadDate;
			}
			set
			{
				this._UploadDate = value;
			}
		}
		
		private string _DataFileLocation;
		public virtual string DataFileLocation
		{
			get
			{
				return this._DataFileLocation;
			}
			set
			{
				this._DataFileLocation = value;
			}
		}
		
		private string _InternalNote;
		public virtual string InternalNote
		{
			get
			{
				return this._InternalNote;
			}
			set
			{
				this._InternalNote = value;
			}
		}
		
		private long? _UserID;
		public virtual long? UserID
		{
			get
			{
				return this._UserID;
			}
			set
			{
				this._UserID = value;
			}
		}
		
		private long? _EquipmentID;
		public virtual long? EquipmentID
		{
			get
			{
				return this._EquipmentID;
			}
			set
			{
				this._EquipmentID = value;
			}
		}
		
		private bool _IsActive;
		public virtual bool IsActive
		{
			get
			{
				return this._IsActive;
			}
			set
			{
				this._IsActive = value;
			}
		}

        private long? _StatusID;
        public virtual long? StatusID
        {
            get
            {
                return this._StatusID;
            }
            set
            {
                this._StatusID = value;
            }
        }

        private string _LastError;
        public virtual string LastError
        {
            get
            {
                return this._LastError;
            }
            set
            {
                this._LastError = value;
            }
        }

        private bool _HasError;
        public virtual bool HasError
        {
            get
            {
                return this._HasError;
            }
            set
            {
                this._HasError = value;
            }
        }

        private PACS_RawDataStatus _PACSRawDataStatus;
        public virtual PACS_RawDataStatus PACSRawDataStatus
        {
            get
            {
                return this._PACSRawDataStatus;
            }
            set
            {
                this._PACSRawDataStatus = value;
            }
        }

        private QRY_Query _QRYQuery;
		public virtual QRY_Query QRYQuery
		{
			get
			{
				return this._QRYQuery;
			}
			set
			{
				this._QRYQuery = value;
			}
		}
		
		private CERT_User _CERTUser;
		public virtual CERT_User CERTUser
		{
			get
			{
				return this._CERTUser;
			}
			set
			{
				this._CERTUser = value;
			}
		}
		
		private CERT_Equipment _CERTEquipment;
		public virtual CERT_Equipment CERTEquipment
		{
			get
			{
				return this._CERTEquipment;
			}
			set
			{
				this._CERTEquipment = value;
			}
		}
		
		private CONTACT_User _CONTACTUser;
		public virtual CONTACT_User CONTACTUser
		{
			get
			{
				return this._CONTACTUser;
			}
			set
			{
				this._CONTACTUser = value;
			}
		}
		
		private CONTACT_Equipment _CONTACTEquipment;
		public virtual CONTACT_Equipment CONTACTEquipment
		{
			get
			{
				return this._CONTACTEquipment;
			}
			set
			{
				this._CONTACTEquipment = value;
			}
		}
		
		//private IList<AUDIT_Record> _AUDITRecords = new List<AUDIT_Record>();
		//public virtual IList<AUDIT_Record> AUDIT_Records
		//{
		//	get
		//	{
		//		return this._AUDITRecords;
		//	}
		//}
		
	}
}
#pragma warning restore 1591
