#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using Excelsior.Domain;

namespace Excelsior.Domain	
{
	public partial class CERT_ImgProcedureList
	{
		private string _ImgProcedureName;
		public virtual string ImgProcedureName
		{
			get
			{
				return this._ImgProcedureName;
			}
			set
			{
				this._ImgProcedureName = value;
			}
		}
		
		private long _ImgProcedureID;
		public virtual long ImgProcedureID
		{
			get
			{
				return this._ImgProcedureID;
			}
			set
			{
				this._ImgProcedureID = value;
			}
		}
		
		private string _ImgProcedureDescription;
		public virtual string ImgProcedureDescription
		{
			get
			{
				return this._ImgProcedureDescription;
			}
			set
			{
				this._ImgProcedureDescription = value;
			}
		}
		
		private long? _DataTypeID;
		public virtual long? DataTypeID
		{
			get
			{
				return this._DataTypeID;
			}
			set
			{
				this._DataTypeID = value;
			}
		}
		
		private string _DICOMAnatomicStructureCodeValue;
		public virtual string DICOMAnatomicStructureCodeValue
		{
			get
			{
				return this._DICOMAnatomicStructureCodeValue;
			}
			set
			{
				this._DICOMAnatomicStructureCodeValue = value;
			}
		}
		
		private string _DICOMAnatomicStructureCodeSchemeDesignator;
		public virtual string DICOMAnatomicStructureCodeSchemeDesignator
		{
			get
			{
				return this._DICOMAnatomicStructureCodeSchemeDesignator;
			}
			set
			{
				this._DICOMAnatomicStructureCodeSchemeDesignator = value;
			}
		}
		
		private string _DICOMAnatomicStructureCodeMeaning;
		public virtual string DICOMAnatomicStructureCodeMeaning
		{
			get
			{
				return this._DICOMAnatomicStructureCodeMeaning;
			}
			set
			{
				this._DICOMAnatomicStructureCodeMeaning = value;
			}
		}
		
		private string _DICOMAcquisitionDeviceCodeValue;
		public virtual string DICOMAcquisitionDeviceCodeValue
		{
			get
			{
				return this._DICOMAcquisitionDeviceCodeValue;
			}
			set
			{
				this._DICOMAcquisitionDeviceCodeValue = value;
			}
		}
		
		private string _DICOMAcquisitionDeviceCodeSchemeDesignator;
		public virtual string DICOMAcquisitionDeviceCodeSchemeDesignator
		{
			get
			{
				return this._DICOMAcquisitionDeviceCodeSchemeDesignator;
			}
			set
			{
				this._DICOMAcquisitionDeviceCodeSchemeDesignator = value;
			}
		}
		
		private string _DICOMAcquisitionDeviceCodeMeaning;
		public virtual string DICOMAcquisitionDeviceCodeMeaning
		{
			get
			{
				return this._DICOMAcquisitionDeviceCodeMeaning;
			}
			set
			{
				this._DICOMAcquisitionDeviceCodeMeaning = value;
			}
		}
		
		private PACS_DataType _PACSDataType;
		public virtual PACS_DataType PACSDataType
		{
			get
			{
				return this._PACSDataType;
			}
			set
			{
				this._PACSDataType = value;
			}
		}
		
		private IList<PACS_TPProcList> _PACSTPProcLists = new List<PACS_TPProcList>();
		public virtual IList<PACS_TPProcList> PACS_TPProcLists
		{
			get
			{
				return this._PACSTPProcLists;
			}
		}
		
		private IList<CERT_User> _CERTUsers = new List<CERT_User>();
		public virtual IList<CERT_User> CERT_Users
		{
			get
			{
				return this._CERTUsers;
			}
		}
		
		private IList<CERT_Equipment> _CERTEquipments = new List<CERT_Equipment>();
		public virtual IList<CERT_Equipment> CERT_Equipments
		{
			get
			{
				return this._CERTEquipments;
			}
		}
		
		private IList<CONTACT_TrialReadingCenter> _CONTACTTrialReadingCenters = new List<CONTACT_TrialReadingCenter>();
		public virtual IList<CONTACT_TrialReadingCenter> CONTACT_TrialReadingCenters
		{
			get
			{
				return this._CONTACTTrialReadingCenters;
			}
		}
		
		private IList<CERT_QuestionList> _CERTQuestionLists = new List<CERT_QuestionList>();
		public virtual IList<CERT_QuestionList> CERT_QuestionLists
		{
			get
			{
				return this._CERTQuestionLists;
			}
		}

        private IList<PACS_Trial> _PACSTrials = new List<PACS_Trial>();
        public virtual IList<PACS_Trial> PACS_Trials
        {
            get
            {
                return this._PACSTrials;
            }
        }
    }
}
#pragma warning restore 1591
