#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using Excelsior.Domain;

namespace Excelsior.Domain	
{
	public partial class CFG_AnimalSpecy
	{
		private long _AnimalSpeciesID;
		public virtual long AnimalSpeciesID
		{
			get
			{
				return this._AnimalSpeciesID;
			}
			set
			{
				this._AnimalSpeciesID = value;
			}
		}
		
		private string _AnimalSpeciesName;
		public virtual string AnimalSpeciesName
		{
			get
			{
				return this._AnimalSpeciesName;
			}
			set
			{
				this._AnimalSpeciesName = value;
			}
		}
		
		private string _AnimalSpeciesDisplayName;
		public virtual string AnimalSpeciesDisplayName
		{
			get
			{
				return this._AnimalSpeciesDisplayName;
			}
			set
			{
				this._AnimalSpeciesDisplayName = value;
			}
		}
		
		private IList<PACS_Trial> _PACSTrials = new List<PACS_Trial>();
		public virtual IList<PACS_Trial> PACS_Trials
		{
			get
			{
				return this._PACSTrials;
			}
		}
		
	}
}
#pragma warning restore 1591
