#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using Excelsior.Domain;

namespace Excelsior.Domain	
{
	public partial class CONTACT_User
	{
		private string _ZipCode;
		public virtual string ZipCode
		{
			get
			{
				return this._ZipCode;
			}
			set
			{
				this._ZipCode = value;
			}
		}
		
		private long _UserID;
		public virtual long UserID
		{
			get
			{
				return this._UserID;
			}
			set
			{
				this._UserID = value;
			}
		}
		
		private string _StateProvince;
		public virtual string StateProvince
		{
			get
			{
				return this._StateProvince;
			}
			set
			{
				this._StateProvince = value;
			}
		}
		
		private string _Prefix;
		public virtual string Prefix
		{
			get
			{
				return this._Prefix;
			}
			set
			{
				this._Prefix = value;
			}
		}
		
		private string _PhoneNumber;
		public virtual string PhoneNumber
		{
			get
			{
				return this._PhoneNumber;
			}
			set
			{
				this._PhoneNumber = value;
			}
		}
		
		private string _MiddleName;
		public virtual string MiddleName
		{
			get
			{
				return this._MiddleName;
			}
			set
			{
				this._MiddleName = value;
			}
		}
		
		private string _LoweredUserName;
		public virtual string LoweredUserName
		{
			get
			{
				return this._LoweredUserName;
			}
			set
			{
				this._LoweredUserName = value;
			}
		}
		
		private string _LoweredEmail;
		public virtual string LoweredEmail
		{
			get
			{
				return this._LoweredEmail;
			}
			set
			{
				this._LoweredEmail = value;
			}
		}
		
		private string _LastName;
		public virtual string LastName
		{
			get
			{
				return this._LastName;
			}
			set
			{
				this._LastName = value;
			}
		}
		
		private string _LanguagePreference;
		public virtual string LanguagePreference
		{
			get
			{
				return this._LanguagePreference;
			}
			set
			{
				this._LanguagePreference = value;
			}
		}
		
		private string _JobTitle;
		public virtual string JobTitle
		{
			get
			{
				return this._JobTitle;
			}
			set
			{
				this._JobTitle = value;
			}
		}
		
		private bool _IsValidated;
		public virtual bool IsValidated
		{
			get
			{
				return this._IsValidated;
			}
			set
			{
				this._IsValidated = value;
			}
		}
		
		private bool _IsActive;
		public virtual bool IsActive
		{
			get
			{
				return this._IsActive;
			}
			set
			{
				this._IsActive = value;
			}
		}
		
		private string _Gender;
		public virtual string Gender
		{
			get
			{
				return this._Gender;
			}
			set
			{
				this._Gender = value;
			}
		}
		
		private string _FirstName;
		public virtual string FirstName
		{
			get
			{
				return this._FirstName;
			}
			set
			{
				this._FirstName = value;
			}
		}
		
		private string _Email;
		public virtual string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				this._Email = value;
			}
		}
		
		private string _City;
		public virtual string City
		{
			get
			{
				return this._City;
			}
			set
			{
				this._City = value;
			}
		}
		
		private Guid? _AspUserID;
		public virtual Guid? AspUserID
		{
			get
			{
				return this._AspUserID;
			}
			set
			{
				this._AspUserID = value;
			}
		}
		
		private long? _AffiliationID;
		public virtual long? AffiliationID
		{
			get
			{
				return this._AffiliationID;
			}
			set
			{
				this._AffiliationID = value;
			}
		}
		
		private string _Address2;
		public virtual string Address2
		{
			get
			{
				return this._Address2;
			}
			set
			{
				this._Address2 = value;
			}
		}
		
		private string _Address1;
		public virtual string Address1
		{
			get
			{
				return this._Address1;
			}
			set
			{
				this._Address1 = value;
			}
		}
		
		private Guid? _RoleId;
		public virtual Guid? RoleId
		{
			get
			{
				return this._RoleId;
			}
			set
			{
				this._RoleId = value;
			}
		}
		
		private long? _CountryID;
		public virtual long? CountryID
		{
			get
			{
				return this._CountryID;
			}
			set
			{
				this._CountryID = value;
			}
		}
		
		private Aspnet_User _AspnetUser;
		public virtual Aspnet_User AspnetUser
		{
			get
			{
				return this._AspnetUser;
			}
			set
			{
				this._AspnetUser = value;
			}
		}
		
		private CONTACT_Affiliation _CONTACTAffiliation;
		public virtual CONTACT_Affiliation CONTACTAffiliation
		{
			get
			{
				return this._CONTACTAffiliation;
			}
			set
			{
				this._CONTACTAffiliation = value;
			}
		}
		
		private Aspnet_Role _AspnetRole;
		public virtual Aspnet_Role AspnetRole
		{
			get
			{
				return this._AspnetRole;
			}
			set
			{
				this._AspnetRole = value;
			}
		}
		
		private CONTACT_Country _CONTACTCountry;
		public virtual CONTACT_Country CONTACTCountry
		{
			get
			{
				return this._CONTACTCountry;
			}
			set
			{
				this._CONTACTCountry = value;
			}
		}
		
		private IList<CONTACT_UserTrial> _CONTACTUserTrials = new List<CONTACT_UserTrial>();
		public virtual IList<CONTACT_UserTrial> CONTACT_UserTrials
		{
			get
			{
				return this._CONTACTUserTrials;
			}
		}
		
		private IList<PACS_Series> _PACSSeries = new List<PACS_Series>();
		public virtual IList<PACS_Series> PACS_Series
		{
			get
			{
				return this._PACSSeries;
			}
		}
		
		private IList<UPLD_UploadInfo> _UPLDUploadInfos = new List<UPLD_UploadInfo>();
		public virtual IList<UPLD_UploadInfo> UPLD_UploadInfos
		{
			get
			{
				return this._UPLDUploadInfos;
			}
		}
		
        //private IList<AUDIT_CRUDAudit> _AUDITCRUDAudits = new List<AUDIT_CRUDAudit>();
        //public virtual IList<AUDIT_CRUDAudit> AUDIT_CRUDAudits
        //{
        //    get
        //    {
        //        return this._AUDITCRUDAudits;
        //    }
        //}
		
		private IList<QRY_Query> _QRYQueries = new List<QRY_Query>();
		public virtual IList<QRY_Query> QRY_Queries
		{
			get
			{
				return this._QRYQueries;
			}
		}
		
		private IList<QRY_Query> _QRYQueries1 = new List<QRY_Query>();
		public virtual IList<QRY_Query> QRY_Queries1
		{
			get
			{
				return this._QRYQueries1;
			}
		}

        private IList<QRY_Message> _QRYMessages = new List<QRY_Message>();
        public virtual IList<QRY_Message> QRY_Messages
        {
            get
            {
                return this._QRYMessages;
            }
        }

        private IList<GRD_Report> _GRDReports = new List<GRD_Report>();
		public virtual IList<GRD_Report> GRD_Reports
		{
			get
			{
				return this._GRDReports;
			}
		}
		
		private IList<DOCU_DocumentUser> _DOCUDocumentUsers = new List<DOCU_DocumentUser>();
		public virtual IList<DOCU_DocumentUser> DOCU_DocumentUsers
		{
			get
			{
				return this._DOCUDocumentUsers;
			}
		}
		
		//private IList<AUDIT_Record> _AUDITRecords = new List<AUDIT_Record>();
		//public virtual IList<AUDIT_Record> AUDIT_Records
		//{
		//	get
		//	{
		//		return this._AUDITRecords;
		//	}
		//}
		
		private IList<PACS_SeriesComment> _PACSSeriesComments = new List<PACS_SeriesComment>();
		public virtual IList<PACS_SeriesComment> PACS_SeriesComments
		{
			get
			{
				return this._PACSSeriesComments;
			}
		}

        private IList<PACS_SeriesAttachment> _PACSSeriesAttachments = new List<PACS_SeriesAttachment>();
        public virtual IList<PACS_SeriesAttachment> PACS_SeriesAttachments
        {
            get
            {
                return this._PACSSeriesAttachments;
            }
        }

        private IList<CERT_UploadInfo> _CERTUploadInfos = new List<CERT_UploadInfo>();
		public virtual IList<CERT_UploadInfo> CERT_UploadInfos
		{
			get
			{
				return this._CERTUploadInfos;
			}
		}
		
		private IList<DOCU_DocumentVersionUser> _DOCUDocumentVersionUsers = new List<DOCU_DocumentVersionUser>();
		public virtual IList<DOCU_DocumentVersionUser> DOCU_DocumentVersionUsers
		{
			get
			{
				return this._DOCUDocumentVersionUsers;
			}
		}
		
		private IList<CONTACT_UserNotification> _CONTACTUserNotifications = new List<CONTACT_UserNotification>();
		public virtual IList<CONTACT_UserNotification> CONTACT_UserNotifications
		{
			get
			{
				return this._CONTACTUserNotifications;
			}
		}
		
		private IList<CONTACT_UserAffiliation> _CONTACTUserAffiliations = new List<CONTACT_UserAffiliation>();
		public virtual IList<CONTACT_UserAffiliation> CONTACT_UserAffiliations
		{
			get
			{
				return this._CONTACTUserAffiliations;
			}
		}
		
		private IList<WF_Sequence> _WFSequences = new List<WF_Sequence>();
		public virtual IList<WF_Sequence> WF_Sequences
		{
			get
			{
				return this._WFSequences;
			}
		}
		
		private IList<CERT_Equipment> _CERTEquipments = new List<CERT_Equipment>();
		public virtual IList<CERT_Equipment> CERT_Equipments
		{
			get
			{
				return this._CERTEquipments;
			}
		}

        private IList<CERT_Equipment> _CERTEquipmentsAssigned = new List<CERT_Equipment>();
        public virtual IList<CERT_Equipment> CERT_EquipmentsAssigned
        {
            get
            {
                return this._CERTEquipmentsAssigned;
            }
        }

        private IList<CERT_User> _CERTUsers = new List<CERT_User>();
		public virtual IList<CERT_User> CERT_Users
		{
			get
			{
				return this._CERTUsers;
			}
		}

        private IList<CERT_User> _CERTUsersAssigned = new List<CERT_User>();
        public virtual IList<CERT_User> CERT_UsersAssigned
        {
            get
            {
                return this._CERTUsersAssigned;
            }
        }

        private IList<BGD_Job> _BGDJobs = new List<BGD_Job>();
		public virtual IList<BGD_Job> BGD_Jobs
		{
			get
			{
				return this._BGDJobs;
			}
		}
		
		private IList<PACS_ProcessedDatum> _PACSProcessedData = new List<PACS_ProcessedDatum>();
		public virtual IList<PACS_ProcessedDatum> PACS_ProcessedData
		{
			get
			{
				return this._PACSProcessedData;
			}
		}
		
		//private IList<AUDIT_Record> _AUDITRecords1 = new List<AUDIT_Record>();
		//public virtual IList<AUDIT_Record> AUDIT_Records1
		//{
		//	get
		//	{
		//		return this._AUDITRecords1;
		//	}
		//}

        private IList<CRF_Datum> _VerifiedCRFData = new List<CRF_Datum>();
        public virtual IList<CRF_Datum> VerifiedCRF_Data
        {
            get
            {
                return this._VerifiedCRFData;
            }
        }

        private IList<CRF_Datum> _SignedCRFData = new List<CRF_Datum>();
        public virtual IList<CRF_Datum> SignedCRF_Data
        {
            get
            {
                return this._SignedCRFData;
            }
        }

        private IList<PACS_Series> _PACSSeriesAssigned = new List<PACS_Series>();
        public virtual IList<PACS_Series> PACS_SeriesAssigned
        {
            get
            {
                return this._PACSSeriesAssigned;
            }
        }
    }
}
#pragma warning restore 1591
