#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using Excelsior.Domain;

namespace Excelsior.Domain	
{
	public partial class CONTACT_Affiliation
	{
		private string _ZipCode;
		public virtual string ZipCode
		{
			get
			{
				return this._ZipCode;
			}
			set
			{
				this._ZipCode = value;
			}
		}
		
		private string _StateProvince;
		public virtual string StateProvince
		{
			get
			{
				return this._StateProvince;
			}
			set
			{
				this._StateProvince = value;
			}
		}
		
		private string _PhoneNumber;
		public virtual string PhoneNumber
		{
			get
			{
				return this._PhoneNumber;
			}
			set
			{
				this._PhoneNumber = value;
			}
		}
		
		private bool _IsValidated;
		public virtual bool IsValidated
		{
			get
			{
				return this._IsValidated;
			}
			set
			{
				this._IsValidated = value;
			}
		}
		
		private bool _IsActive;
		public virtual bool IsActive
		{
			get
			{
				return this._IsActive;
			}
			set
			{
				this._IsActive = value;
			}
		}
		
		private string _City;
		public virtual string City
		{
			get
			{
				return this._City;
			}
			set
			{
				this._City = value;
			}
		}
		
		private string _AffiliationName;
		public virtual string AffiliationName
		{
			get
			{
				return this._AffiliationName;
			}
			set
			{
				this._AffiliationName = value;
			}
		}
		
		private long _AffiliationID;
		public virtual long AffiliationID
		{
			get
			{
				return this._AffiliationID;
			}
			set
			{
				this._AffiliationID = value;
			}
		}
		
		private string _Address2;
		public virtual string Address2
		{
			get
			{
				return this._Address2;
			}
			set
			{
				this._Address2 = value;
			}
		}
		
		private string _Address1;
		public virtual string Address1
		{
			get
			{
				return this._Address1;
			}
			set
			{
				this._Address1 = value;
			}
		}

        private string _LogoURL;
        public virtual string LogoURL
        {
            get
            {
                return this._LogoURL;
            }
            set
            {
                this._LogoURL = value;
            }
        }

        private long? _CountryID;
		public virtual long? CountryID
		{
			get
			{
				return this._CountryID;
			}
			set
			{
				this._CountryID = value;
			}
		}
		
		private CONTACT_Country _CONTACTCountry;
		public virtual CONTACT_Country CONTACTCountry
		{
			get
			{
				return this._CONTACTCountry;
			}
			set
			{
				this._CONTACTCountry = value;
			}
		}
		
		private IList<CONTACT_User> _CONTACTUsers = new List<CONTACT_User>();
		public virtual IList<CONTACT_User> CONTACT_Users
		{
			get
			{
				return this._CONTACTUsers;
			}
		}
		
		private IList<CONTACT_TrialSponsor> _CONTACTTrialSponsors = new List<CONTACT_TrialSponsor>();
		public virtual IList<CONTACT_TrialSponsor> CONTACT_TrialSponsors
		{
			get
			{
				return this._CONTACTTrialSponsors;
			}
		}
		
		private IList<CONTACT_Equipment> _CONTACTEquipments = new List<CONTACT_Equipment>();
		public virtual IList<CONTACT_Equipment> CONTACT_Equipments
		{
			get
			{
				return this._CONTACTEquipments;
			}
		}
		
		private IList<PACS_Site> _PACSSites = new List<PACS_Site>();
		public virtual IList<PACS_Site> PACS_Sites
		{
			get
			{
				return this._PACSSites;
			}
		}
		
		private IList<CONTACT_TrialReadingCenter> _CONTACTTrialReadingCenters = new List<CONTACT_TrialReadingCenter>();
		public virtual IList<CONTACT_TrialReadingCenter> CONTACT_TrialReadingCenters
		{
			get
			{
				return this._CONTACTTrialReadingCenters;
			}
		}
		
		private IList<CONTACT_UserAffiliation> _CONTACTUserAffiliations = new List<CONTACT_UserAffiliation>();
		public virtual IList<CONTACT_UserAffiliation> CONTACT_UserAffiliations
		{
			get
			{
				return this._CONTACTUserAffiliations;
			}
		}
		
	}
}
#pragma warning restore 1591
