#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using Excelsior.Domain;

namespace Excelsior.Domain	
{
	public partial class CONTACT_NotificationRole
	{
		private long _NotificationRoleID;
		public virtual long NotificationRoleID
		{
			get
			{
				return this._NotificationRoleID;
			}
			set
			{
				this._NotificationRoleID = value;
			}
		}
		
		private long? _NotificationID;
		public virtual long? NotificationID
		{
			get
			{
				return this._NotificationID;
			}
			set
			{
				this._NotificationID = value;
			}
		}
		
		private Guid? _RoleId;
		public virtual Guid? RoleId
		{
			get
			{
				return this._RoleId;
			}
			set
			{
				this._RoleId = value;
			}
		}
		
		private Aspnet_Role _AspnetRole;
		public virtual Aspnet_Role AspnetRole
		{
			get
			{
				return this._AspnetRole;
			}
			set
			{
				this._AspnetRole = value;
			}
		}
		
		private CONTACT_Notification _CONTACTNotification;
		public virtual CONTACT_Notification CONTACTNotification
		{
			get
			{
				return this._CONTACTNotification;
			}
			set
			{
				this._CONTACTNotification = value;
			}
		}
		
	}
}
#pragma warning restore 1591
