#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using Excelsior.Domain;

namespace Excelsior.Domain	
{
	public partial class CONTACT_Notification
	{
		private long _NotificationID;
		public virtual long NotificationID
		{
			get
			{
				return this._NotificationID;
			}
			set
			{
				this._NotificationID = value;
			}
		}
		
		private string _NotificationName;
		public virtual string NotificationName
		{
			get
			{
				return this._NotificationName;
			}
			set
			{
				this._NotificationName = value;
			}
		}
		
		private string _NotificationDesc;
		public virtual string NotificationDesc
		{
			get
			{
				return this._NotificationDesc;
			}
			set
			{
				this._NotificationDesc = value;
			}
		}
		
		private string _NotificationMsg;
		public virtual string NotificationMsg
		{
			get
			{
				return this._NotificationMsg;
			}
			set
			{
				this._NotificationMsg = value;
			}
		}
		
		private bool _IsPrivate;
		public virtual bool IsPrivate
		{
			get
			{
				return this._IsPrivate;
			}
			set
			{
				this._IsPrivate = value;
			}
		}
		
		private IList<CONTACT_UserNotification> _CONTACTUserNotifications = new List<CONTACT_UserNotification>();
		public virtual IList<CONTACT_UserNotification> CONTACT_UserNotifications
		{
			get
			{
				return this._CONTACTUserNotifications;
			}
		}
		
		private IList<CONTACT_NotificationRole> _CONTACTNotificationRoles = new List<CONTACT_NotificationRole>();
		public virtual IList<CONTACT_NotificationRole> CONTACT_NotificationRoles
		{
			get
			{
				return this._CONTACTNotificationRoles;
			}
		}
		
	}
}
#pragma warning restore 1591
