#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using Excelsior.Domain;

namespace Excelsior.Domain	
{
	public partial class CONTACT_EquipmentModel
	{
		private string _ManufacturerName;
		public virtual string ManufacturerName
		{
			get
			{
				return this._ManufacturerName;
			}
			set
			{
				this._ManufacturerName = value;
			}
		}
		
		private string _ManufacturerModel;
		public virtual string ManufacturerModel
		{
			get
			{
				return this._ManufacturerModel;
			}
			set
			{
				this._ManufacturerModel = value;
			}
		}
		
		private string _EquipmentType;
		public virtual string EquipmentType
		{
			get
			{
				return this._EquipmentType;
			}
			set
			{
				this._EquipmentType = value;
			}
		}
		
		private long _EquipmentModelID;
		public virtual long EquipmentModelID
		{
			get
			{
				return this._EquipmentModelID;
			}
			set
			{
				this._EquipmentModelID = value;
			}
		}
		
		private IList<CONTACT_Equipment> _CONTACTEquipments = new List<CONTACT_Equipment>();
		public virtual IList<CONTACT_Equipment> CONTACT_Equipments
		{
			get
			{
				return this._CONTACTEquipments;
			}
		}
		
	}
}
#pragma warning restore 1591
