#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using Excelsior.Domain;

namespace Excelsior.Domain	
{
	public partial class CONTACT_Equipment
	{
		private string _StationName;
		public virtual string StationName
		{
			get
			{
				return this._StationName;
			}
			set
			{
				this._StationName = value;
			}
		}
		
		private string _SoftwareVersion;
		public virtual string SoftwareVersion
		{
			get
			{
				return this._SoftwareVersion;
			}
			set
			{
				this._SoftwareVersion = value;
			}
		}
		
		private string _SeconarySerialNum;
		public virtual string SeconarySerialNum
		{
			get
			{
				return this._SeconarySerialNum;
			}
			set
			{
				this._SeconarySerialNum = value;
			}
		}
		
		private string _OtherSerialNum;
		public virtual string OtherSerialNum
		{
			get
			{
				return this._OtherSerialNum;
			}
			set
			{
				this._OtherSerialNum = value;
			}
		}
		
		private string _Notes;
		public virtual string Notes
		{
			get
			{
				return this._Notes;
			}
			set
			{
				this._Notes = value;
			}
		}
		
		private string _MainSerialNum;
		public virtual string MainSerialNum
		{
			get
			{
				return this._MainSerialNum;
			}
			set
			{
				this._MainSerialNum = value;
			}
		}
		
		private DateTime? _LastCalibrationTime;
		public virtual DateTime? LastCalibrationTime
		{
			get
			{
				return this._LastCalibrationTime;
			}
			set
			{
				this._LastCalibrationTime = value;
			}
		}
		
		private DateTime? _LastCalibrationDate;
		public virtual DateTime? LastCalibrationDate
		{
			get
			{
				return this._LastCalibrationDate;
			}
			set
			{
				this._LastCalibrationDate = value;
			}
		}
		
		private bool _IsValidated;
		public virtual bool IsValidated
		{
			get
			{
				return this._IsValidated;
			}
			set
			{
				this._IsValidated = value;
			}
		}
		
		private bool _IsActive;
		public virtual bool IsActive
		{
			get
			{
				return this._IsActive;
			}
			set
			{
				this._IsActive = value;
			}
		}
		
		private string _FirmwareVersion;
		public virtual string FirmwareVersion
		{
			get
			{
				return this._FirmwareVersion;
			}
			set
			{
				this._FirmwareVersion = value;
			}
		}
		
		private long? _EquipmentModelID;
		public virtual long? EquipmentModelID
		{
			get
			{
				return this._EquipmentModelID;
			}
			set
			{
				this._EquipmentModelID = value;
			}
		}
		
		private long _EquipmentID;
		public virtual long EquipmentID
		{
			get
			{
				return this._EquipmentID;
			}
			set
			{
				this._EquipmentID = value;
			}
		}
		
		private long? _AffiliationID;
		public virtual long? AffiliationID
		{
			get
			{
				return this._AffiliationID;
			}
			set
			{
				this._AffiliationID = value;
			}
		}
		
		private CONTACT_EquipmentModel _CONTACTEquipmentModel;
		public virtual CONTACT_EquipmentModel CONTACTEquipmentModel
		{
			get
			{
				return this._CONTACTEquipmentModel;
			}
			set
			{
				this._CONTACTEquipmentModel = value;
			}
		}
		
		private CONTACT_Affiliation _CONTACTAffiliation;
		public virtual CONTACT_Affiliation CONTACTAffiliation
		{
			get
			{
				return this._CONTACTAffiliation;
			}
			set
			{
				this._CONTACTAffiliation = value;
			}
		}
		
		private IList<CERT_Equipment> _CERTEquipments = new List<CERT_Equipment>();
		public virtual IList<CERT_Equipment> CERT_Equipments
		{
			get
			{
				return this._CERTEquipments;
			}
		}
		
		private IList<PACS_Series> _PACSSeries = new List<PACS_Series>();
		public virtual IList<PACS_Series> PACS_Series
		{
			get
			{
				return this._PACSSeries;
			}
		}
		
		private IList<CERT_UploadInfo> _CERTUploadInfos = new List<CERT_UploadInfo>();
		public virtual IList<CERT_UploadInfo> CERT_UploadInfos
		{
			get
			{
				return this._CERTUploadInfos;
			}
		}
		
	}
}
#pragma warning restore 1591
