#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using Excelsior.Domain;

namespace Excelsior.Domain	
{
	public partial class CONTACT_UserTrial
	{
		private long? _UserID;
		public virtual long? UserID
		{
			get
			{
				return this._UserID;
			}
			set
			{
				this._UserID = value;
			}
		}
		
		private long? _TrialID;
		public virtual long? TrialID
		{
			get
			{
				return this._TrialID;
			}
			set
			{
				this._TrialID = value;
			}
		}
		
		private long _UserTrialID;
		public virtual long UserTrialID
		{
			get
			{
				return this._UserTrialID;
			}
			set
			{
				this._UserTrialID = value;
			}
		}
		
		private bool _IsActive;
		public virtual bool IsActive
		{
			get
			{
				return this._IsActive;
			}
			set
			{
				this._IsActive = value;
			}
		}
		
		private CONTACT_User _CONTACTUser;
		public virtual CONTACT_User CONTACTUser
		{
			get
			{
				return this._CONTACTUser;
			}
			set
			{
				this._CONTACTUser = value;
			}
		}
		
		private PACS_Trial _PACSTrial;
		public virtual PACS_Trial PACSTrial
		{
			get
			{
				return this._PACSTrial;
			}
			set
			{
				this._PACSTrial = value;
			}
		}
		
		private IList<CERT_User> _CERTUsers = new List<CERT_User>();
		public virtual IList<CERT_User> CERT_Users
		{
			get
			{
				return this._CERTUsers;
			}
		}
		
	}
}
#pragma warning restore 1591
