#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using Excelsior.Domain;

namespace Excelsior.Domain	
{
	public partial class CONTACT_Country
	{
		private long _CountryID;
		public virtual long CountryID
		{
			get
			{
				return this._CountryID;
			}
			set
			{
				this._CountryID = value;
			}
		}
		
		private string _CountryName;
		public virtual string CountryName
		{
			get
			{
				return this._CountryName;
			}
			set
			{
				this._CountryName = value;
			}
		}
		
		private IList<CONTACT_Affiliation> _CONTACTAffiliations = new List<CONTACT_Affiliation>();
		public virtual IList<CONTACT_Affiliation> CONTACT_Affiliations
		{
			get
			{
				return this._CONTACTAffiliations;
			}
		}
		
		private IList<CONTACT_User> _CONTACTUsers = new List<CONTACT_User>();
		public virtual IList<CONTACT_User> CONTACT_Users
		{
			get
			{
				return this._CONTACTUsers;
			}
		}
		
	}
}
#pragma warning restore 1591
