#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using Excelsior.Domain;

namespace Excelsior.Domain	
{
	public partial class CRF_TemplateDependencySource
    {
		private long _CRFTemplateDependencySourceID;
		public virtual long CRFTemplateDependencySourceID
        {
			get
			{
				return this._CRFTemplateDependencySourceID;
			}
			set
			{
				this._CRFTemplateDependencySourceID = value;
			}
		}

        private long? _CRFTemplateDependencyID;
        public virtual long? CRFTemplateDependencyID
        {
            get
            {
                return this._CRFTemplateDependencyID;
            }
            set
            {
                this._CRFTemplateDependencyID = value;
            }
        }

        private long? _SourceAnswerID;
        public virtual long? SourceAnswerID
        {
            get
            {
                return this._SourceAnswerID;
            }
            set
            {
                this._SourceAnswerID = value;
            }
        }

        private long? _SourceQuestionID;
        public virtual long? SourceQuestionID
        {
            get
            {
                return this._SourceQuestionID;
            }
            set
            {
                this._SourceQuestionID = value;
            }
        }

		private CRF_TemplateAnswer _SourceAnswer;
		public virtual CRF_TemplateAnswer SourceAnswer
        {
			get
			{
				return this._SourceAnswer;
			}
			set
			{
				this._SourceAnswer = value;
			}
		}

        private CRF_TemplateQuestion _SourceQuestion;
        public virtual CRF_TemplateQuestion SourceQuestion
        {
            get
            {
                return this._SourceQuestion;
            }
            set
            {
                this._SourceQuestion = value;
            }
        }

        private CRF_TemplateDependency _CRFTemplateDependency;
        public virtual CRF_TemplateDependency CRFTemplateDependency
        {
            get
            {
                return this._CRFTemplateDependency;
            }
            set
            {
                this._CRFTemplateDependency = value;
            }
        }
	}
}
#pragma warning restore 1591
