#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using Excelsior.Domain;

namespace Excelsior.Domain	
{
	public partial class CRF_TemplateGroup
    {
		private long _CRFTemplateGroupID;
		public virtual long CRFTemplateGroupID
        {
			get
			{
				return this._CRFTemplateGroupID;
			}
			set
			{
				this._CRFTemplateGroupID = value;
			}
		}

        private long? _CRFTemplateID;
        public virtual long? CRFTemplateID
        {
            get
            {
                return this._CRFTemplateID;
            }
            set
            {
                this._CRFTemplateID = value;
            }
        }

        private string _GroupName;
		public virtual string GroupName
        {
			get
			{
				return this._GroupName;
			}
			set
			{
				this._GroupName = value;
			}
		}

        private int _GroupSeq;
        public virtual int GroupSeq
        {
            get
            {
                return this._GroupSeq;
            }
            set
            {
                this._GroupSeq = value;
            }
        }

        private CRF_Template _CRFTemplate;
        public virtual CRF_Template CRFTemplate
        {
            get
            {
                return this._CRFTemplate;
            }
            set
            {
                this._CRFTemplate = value;
            }
        }

        private IList<CRF_TemplateQuestion> _CRFTemplateQuestions = new List<CRF_TemplateQuestion>();
		public virtual IList<CRF_TemplateQuestion> CRF_TemplateQuestions
        {
			get
			{
				return this._CRFTemplateQuestions;
			}
		}

        private IList<CRF_TemplateDependency> _CRFTemplateDependencies = new List<CRF_TemplateDependency>();
        public virtual IList<CRF_TemplateDependency> CRF_TemplateDependencies
        {
            get
            {
                return this._CRFTemplateDependencies;
            }
        }
    }
}
#pragma warning restore 1591
