#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using Excelsior.Domain;

namespace Excelsior.Domain	
{
	public partial class CRF_AnswerType
    {
		private long _CRFAnswerTypeID;
		public virtual long CRFAnswerTypeID
        {
			get
			{
				return this._CRFAnswerTypeID;
			}
			set
			{
				this._CRFAnswerTypeID = value;
			}
		}

		private string _AnswerTypeName;
		public virtual string AnswerTypeName
        {
			get
			{
				return this._AnswerTypeName;
			}
			set
			{
				this._AnswerTypeName = value;
			}
		}

        private bool _IsActive;
        public virtual bool IsActive
        {
            get
            {
                return this._IsActive;
            }
            set
            {
                this._IsActive = value;
            }
        }

        private IList<CRF_TemplateQuestion> _CRFTemplateQuestions = new List<CRF_TemplateQuestion>();
        public virtual IList<CRF_TemplateQuestion> CRF_TemplateQuestions
        {
            get
            {
                return this._CRFTemplateQuestions;
            }
        }
    }
}
#pragma warning restore 1591
