#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using Excelsior.Domain;

namespace Excelsior.Domain	
{
	public partial class CRF_Datum
	{
		private long _CRFDataID;
		public virtual long CRFDataID
        {
			get
			{
				return this._CRFDataID;
			}
			set
			{
				this._CRFDataID = value;
			}
		}

        private long? _CRFTemplateID;
        public virtual long? CRFTemplateID
        {
            get
            {
                return this._CRFTemplateID;
            }
            set
            {
                this._CRFTemplateID = value;
            }
        }

        private long? _VerifiedByID;
		public virtual long? VerifiedByID
        {
			get
			{
				return this._VerifiedByID;
			}
			set
			{
				this._VerifiedByID = value;
			}
		}

        private DateTime? _VerifiedDateTime;
        public virtual DateTime? VerifiedDateTime
        {
            get
            {
                return this._VerifiedDateTime;
            }
            set
            {
                this._VerifiedDateTime = value;
            }
        }

        private long? _SignedByID;
        public virtual long? SignedByID
        {
            get
            {
                return this._SignedByID;
            }
            set
            {
                this._SignedByID = value;
            }
        }

        private DateTime? _SignedDateTime;
        public virtual DateTime? SignedDateTime
        {
            get
            {
                return this._SignedDateTime;
            }
            set
            {
                this._SignedDateTime = value;
            }
        }

		private bool _IsActive;
		public virtual bool IsActive
		{
			get
			{
				return this._IsActive;
			}
			set
			{
				this._IsActive = value;
			}
		}

        private long? _SeriesID;
		public virtual long? SeriesID
		{
			get
			{
				return this._SeriesID;
			}
			set
			{
				this._SeriesID = value;
			}
		}

        private CRF_Template _CRFTemplate;
        public virtual CRF_Template CRFTemplate
        {
            get
            {
                return this._CRFTemplate;
            }
            set
            {
                this._CRFTemplate = value;
            }
        }

        private PACS_Series _PACSSeries;
        public virtual PACS_Series PACSSeries
        {
            get
            {
                return this._PACSSeries;
            }
            set
            {
                this._PACSSeries = value;
            }
        }

        private CONTACT_User _VerifiedBy;
		public virtual CONTACT_User VerifiedBy
        {
			get
			{
				return this._VerifiedBy;
			}
			set
			{
				this._VerifiedBy = value;
			}
		}

        private CONTACT_User _SignedBy;
        public virtual CONTACT_User SignedBy
        {
            get
            {
                return this._SignedBy;
            }
            set
            {
                this._SignedBy = value;
            }
        }

        private IList<CRF_DataRELREC> _SourceCRFDataRELRECs = new List<CRF_DataRELREC>();
        public virtual IList<CRF_DataRELREC> SourceCRF_DataRELRECs
        {
            get
            {
                return this._SourceCRFDataRELRECs;
            }
        }

        private IList<CRF_DataRELREC> _TargetCRFDataRELRECs = new List<CRF_DataRELREC>();
        public virtual IList<CRF_DataRELREC> TargetCRF_DataRELRECs
        {
            get
            {
                return this._TargetCRFDataRELRECs;
            }
        }

        private IList<CRF_DataResult> _CRFDataResults = new List<CRF_DataResult>();
		public virtual IList<CRF_DataResult> CRF_DataResults
		{
			get
			{
				return this._CRFDataResults;
			}
		}
		
		private IList<MEA_Measurement> _MEAMeasurements = new List<MEA_Measurement>();
		public virtual IList<MEA_Measurement> MEA_Measurements
		{
			get
			{
				return this._MEAMeasurements;
			}
		}		
	}
}
#pragma warning restore 1591
