#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using Excelsior.Domain;

namespace Excelsior.Domain	
{
	public partial class CRF_AnswerValidation
    {
        private long _CRFAnswerValidationID;
        public virtual long CRFAnswerValidationID
        {
            get
            {
                return this._CRFAnswerValidationID;
            }
            set
            {
                this._CRFAnswerValidationID = value;
            }
        }

        private long? _TrialID;
        public virtual long? TrialID
        {
            get
            {
                return this._TrialID;
            }
            set
            {
                this._TrialID = value;
            }
        }

        private string _Control;
		public virtual string Control
        {
			get
			{
				return this._Control;
			}
			set
			{
				this._Control = value;
			}
		}

        private string _Mask;
        public virtual string Mask
        {
            get
            {
                return this._Mask;
            }
            set
            {
                this._Mask = value;
            }
        }

        private string _ToolTip;
        public virtual string ToolTip
        {
            get
            {
                return this._ToolTip;
            }
            set
            {
                this._ToolTip = value;
            }
        }

        private string _Unit;
        public virtual string Unit
        {
            get
            {
                return this._Unit;
            }
            set
            {
                this._Unit = value;
            }
        }

        private string _Max;
        public virtual string Max
        {
            get
            {
                return this._Max;
            }
            set
            {
                this._Max = value;
            }
        }

        private string _Min;
        public virtual string Min
        {
            get
            {
                return this._Min;
            }
            set
            {
                this._Min = value;
            }
        }

        private string _Tick;
        public virtual string Tick
        {
            get
            {
                return this._Tick;
            }
            set
            {
                this._Tick = value;
            }
        }

        private string _Name;
        public virtual string Name
        {
            get
            {
                return this._Name;
            }
            set
            {
                this._Name = value;
            }
        }

        private string _Description;
        public virtual string Description
        {
            get
            {
                return this._Description;
            }
            set
            {
                this._Description = value;
            }
        }

        private bool _IsActive;
        public virtual bool IsActive
        {
            get
            {
                return this._IsActive;
            }
            set
            {
                this._IsActive = value;
            }
        }

        private PACS_Trial _PACSTrial;
        public virtual PACS_Trial PACSTrial
        {
            get
            {
                return this._PACSTrial;
            }
            set
            {
                this._PACSTrial = value;
            }
        }

        private IList<CRF_TemplateQuestion> _CRFTemplateQuestions = new List<CRF_TemplateQuestion>();
        public virtual IList<CRF_TemplateQuestion> CRF_TemplateQuestions
        {
            get
            {
                return this._CRFTemplateQuestions;
            }
        }
    }
}
#pragma warning restore 1591
