#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using Excelsior.Domain;

namespace Excelsior.Domain	
{
	public partial class CRF_DataRELREC
    {
		private long _CRFDataRELRECID;
		public virtual long CRFDataRELRECID
        {
			get
			{
				return this._CRFDataRELRECID;
			}
			set
			{
				this._CRFDataRELRECID = value;
			}
		}

        private long? _SourceCRFDataID;
        public virtual long? SourceCRFDataID
        {
            get
            {
                return this._SourceCRFDataID;
            }
            set
            {
                this._SourceCRFDataID = value;
            }
        }

        private long? _TargetCRFDataID;
        public virtual long? TargetCRFDataID
        {
            get
            {
                return this._TargetCRFDataID;
            }
            set
            {
                this._TargetCRFDataID = value;
            }
        }

        private CRF_Datum _SourceCRFData;
		public virtual CRF_Datum SourceCRFData
        {
			get
			{
				return this._SourceCRFData;
			}
			set
			{
				this._SourceCRFData = value;
			}
		}

        private CRF_Datum _TargetCRFData;
        public virtual CRF_Datum TargetCRFData
        {
            get
            {
                return this._TargetCRFData;
            }
            set
            {
                this._TargetCRFData = value;
            }
        }
	}
}
#pragma warning restore 1591
