#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using Excelsior.Domain;

namespace Excelsior.Domain	
{
	public partial class CRF_TemplateAnswer
	{
		private long _CRFTemplateAnswerID;
		public virtual long CRFTemplateAnswerID
        {
			get
			{
				return this._CRFTemplateAnswerID;
			}
			set
			{
				this._CRFTemplateAnswerID = value;
			}
		}

        private long? _CRFTemplateQuestionID;
        public virtual long? CRFTemplateQuestionID
        {
            get
            {
                return this._CRFTemplateQuestionID;
            }
            set
            {
                this._CRFTemplateQuestionID = value;
            }
        }

        private string _AnswerString;
        public virtual string AnswerString
        {
            get
            {
                return this._AnswerString;
            }
            set
            {
                this._AnswerString = value;
            }
        }

        private string _AltAnswerString;
        public virtual string AltAnswerString
        {
            get
            {
                return this._AltAnswerString;
            }
            set
            {
                this._AltAnswerString = value;
            }
        }

        private int _AnswerSeq;
		public virtual int AnswerSeq
        {
			get
			{
				return this._AnswerSeq;
			}
			set
			{
				this._AnswerSeq = value;
			}
		}

        private bool _IsActive;
        public virtual bool IsActive
        {
            get
            {
                return this._IsActive;
            }
            set
            {
                this._IsActive = value;
            }
        }

        private CRF_TemplateQuestion _CRFTemplateQuestion;
		public virtual CRF_TemplateQuestion CRFTemplateQuestion
        {
			get
			{
				return this._CRFTemplateQuestion;
			}
			set
			{
				this._CRFTemplateQuestion = value;
			}
		}

        private IList<CRF_DataResult> _CRFDataResults = new List<CRF_DataResult>();
        public virtual IList<CRF_DataResult> CRF_DataResults
        {
            get
            {
                return this._CRFDataResults;
            }
        }

        private IList<CRF_TemplateDependencySource> _CRFTemplateDependencySources = new List<CRF_TemplateDependencySource>();
        public virtual IList<CRF_TemplateDependencySource> CRF_TemplateDependencySources
        {
            get
            {
                return this._CRFTemplateDependencySources;
            }
        }

        private IList<CRF_TemplateDependency> _CRFTemplateDependencies = new List<CRF_TemplateDependency>();
        public virtual IList<CRF_TemplateDependency> CRF_TemplateDependencies
        {
            get
            {
                return this._CRFTemplateDependencies;
            }
        }
    }
}
#pragma warning restore 1591
