#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using Excelsior.Domain;

namespace Excelsior.Domain	
{
	public partial class CRF_DataResult
	{
		private long _CRFDataResultID;
		public virtual long CRFDataResultID
		{
			get
			{
				return this._CRFDataResultID;
			}
			set
			{
				this._CRFDataResultID = value;
			}
		}
		
		private long? _CRFDataID;
		public virtual long? CRFDataID
        {
			get
			{
				return this._CRFDataID;
			}
			set
			{
				this._CRFDataID = value;
			}
		}

        private long? _CRFTemplateQuestionID;
        public virtual long? CRFTemplateQuestionID
        {
            get
            {
                return this._CRFTemplateQuestionID;
            }
            set
            {
                this._CRFTemplateQuestionID = value;
            }
        }

        private string _AnswerString;
		public virtual string AnswerString
        {
			get
			{
				return this._AnswerString;
			}
			set
			{
				this._AnswerString = value;
			}
		}

        private long? _MeasurementID;
		public virtual long? MeasurementID
        {
			get
			{
				return this._MeasurementID;
			}
			set
			{
				this._MeasurementID = value;
			}
		}
		
		private string _Laterality;
		public virtual string Laterality
		{
			get
			{
				return this._Laterality;
			}
			set
			{
				this._Laterality = value;
			}
		}

        private bool _IsActive;
        public virtual bool IsActive
        {
            get
            {
                return this._IsActive;
            }
            set
            {
                this._IsActive = value;
            }
        }

        private MEA_Measurement _MEAMeasurement;
		public virtual MEA_Measurement MEAMeasurement
		{
			get
			{
				return this._MEAMeasurement;
			}
			set
			{
				this._MEAMeasurement = value;
			}
		}
		
		private CRF_Datum _CRFData;
		public virtual CRF_Datum CRFData
		{
			get
			{
				return this._CRFData;
			}
			set
			{
				this._CRFData = value;
			}
		}

        private CRF_TemplateQuestion _CRFTemplateQuestion;
        public virtual CRF_TemplateQuestion CRFTemplateQuestion
        {
            get
            {
                return this._CRFTemplateQuestion;
            }
            set
            {
                this._CRFTemplateQuestion = value;
            }
        }

        private IList<CRF_TemplateAnswer> _CRFTemplateAnswers = new List<CRF_TemplateAnswer>();
        public virtual IList<CRF_TemplateAnswer> CRF_TemplateAnswers
        {
            get
            {
                return this._CRFTemplateAnswers;
            }
        }
    }
}
#pragma warning restore 1591
