#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using Excelsior.Domain;

namespace Excelsior.Domain	
{
	public partial class CRF_TemplateQuestionTag
    {
		private long _CRFTemplateQuestionTagID;
		public virtual long CRFTemplateQuestionTagID
        {
			get
			{
				return this._CRFTemplateQuestionTagID;
			}
			set
			{
				this._CRFTemplateQuestionTagID = value;
			}
		}

		private string _QuestionTagName;
		public virtual string QuestionTagName
        {
			get
			{
				return this._QuestionTagName;
			}
			set
			{
				this._QuestionTagName = value;
			}
		}

		private IList<CRF_TemplateQuestion> _CRFTemplateQuestions = new List<CRF_TemplateQuestion>();
		public virtual IList<CRF_TemplateQuestion> CRF_TemplateQuestions
        {
			get
			{
				return this._CRFTemplateQuestions;
			}
		}	
	}
}
#pragma warning restore 1591
