#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using Excelsior.Domain;

namespace Excelsior.Domain	
{
	public partial class CRF_TemplateDependency
    {
		private long _CRFTemplateDependencyID;
		public virtual long CRFTemplateDependencyID
        {
			get
			{
				return this._CRFTemplateDependencyID;
			}
			set
			{
				this._CRFTemplateDependencyID = value;
			}
		}

        private long? _CRFTemplateGroupID;
        public virtual long? CRFTemplateGroupID
        {
            get
            {
                return this._CRFTemplateGroupID;
            }
            set
            {
                this._CRFTemplateGroupID = value;
            }
        }

        private long? _TargetQuestionID;
        public virtual long? TargetQuestionID
        {
            get
            {
                return this._TargetQuestionID;
            }
            set
            {
                this._TargetQuestionID = value;
            }
        }

        private long? _TargetAnswerID;
        public virtual long? TargetAnswerID
        {
            get
            {
                return this._TargetAnswerID;
            }
            set
            {
                this._TargetAnswerID = value;
            }
        }

		private bool _ActionEnable;
		public virtual bool ActionEnable
        {
			get
			{
				return this._ActionEnable;
			}
			set
			{
				this._ActionEnable = value;
			}
		}

        private string _Expression;
        public virtual string Expression
        {
            get
            {
                return this._Expression;
            }
            set
            {
                this._Expression = value;
            }
        }

        private CRF_TemplateGroup _CRFTemplateGroup;
        public virtual CRF_TemplateGroup CRFTemplateGroup
        {
            get
            {
                return this._CRFTemplateGroup;
            }
            set
            {
                this._CRFTemplateGroup = value;
            }
        }

        private CRF_TemplateQuestion _TargetQuestion;
        public virtual CRF_TemplateQuestion TargetQuestion
        {
            get
            {
                return this._TargetQuestion;
            }
            set
            {
                this._TargetQuestion = value;
            }
        }

        private CRF_TemplateAnswer _TargetAnswer;
        public virtual CRF_TemplateAnswer TargetAnswer
        {
            get
            {
                return this._TargetAnswer;
            }
            set
            {
                this._TargetAnswer = value;
            }
        }

        private IList<CRF_TemplateDependencySource> _CRFTemplateDependencySources = new List<CRF_TemplateDependencySource>();
        public virtual IList<CRF_TemplateDependencySource> CRF_TemplateDependencySources
        {
            get
            {
                return this._CRFTemplateDependencySources;
            }
        }
    }
}
#pragma warning restore 1591
