#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using Excelsior.Domain;

namespace Excelsior.Domain	
{
	public partial class DOCU_DocumentVersionUser
	{
		private long _DocumentVersionUserID;
		public virtual long DocumentVersionUserID
		{
			get
			{
				return this._DocumentVersionUserID;
			}
			set
			{
				this._DocumentVersionUserID = value;
			}
		}
		
		private long? _UserID;
		public virtual long? UserID
		{
			get
			{
				return this._UserID;
			}
			set
			{
				this._UserID = value;
			}
		}
		
		private DateTime? _LastReadDate;
		public virtual DateTime? LastReadDate
		{
			get
			{
				return this._LastReadDate;
			}
			set
			{
				this._LastReadDate = value;
			}
		}
		
		private long? _DocumentVersionID;
		public virtual long? DocumentVersionID
		{
			get
			{
				return this._DocumentVersionID;
			}
			set
			{
				this._DocumentVersionID = value;
			}
		}
		
		private DOCU_DocumentVersion _DOCUDocumentVersion;
		public virtual DOCU_DocumentVersion DOCUDocumentVersion
		{
			get
			{
				return this._DOCUDocumentVersion;
			}
			set
			{
				this._DOCUDocumentVersion = value;
			}
		}
		
		private CONTACT_User _CONTACTUser;
		public virtual CONTACT_User CONTACTUser
		{
			get
			{
				return this._CONTACTUser;
			}
			set
			{
				this._CONTACTUser = value;
			}
		}
		
	}
}
#pragma warning restore 1591
