#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using Excelsior.Domain;

namespace Excelsior.Domain	
{
	public partial class DOCU_AuthorizationType
	{
		private long _DocuAuthorizationTypeID;
		public virtual long DocuAuthorizationTypeID
		{
			get
			{
				return this._DocuAuthorizationTypeID;
			}
			set
			{
				this._DocuAuthorizationTypeID = value;
			}
		}
		
		private string _DocuAuthorizationDes;
		public virtual string DocuAuthorizationDes
		{
			get
			{
				return this._DocuAuthorizationDes;
			}
			set
			{
				this._DocuAuthorizationDes = value;
			}
		}
		
		private IList<DOCU_DocumentGroup> _DOCUDocumentGroups = new List<DOCU_DocumentGroup>();
		public virtual IList<DOCU_DocumentGroup> DOCU_DocumentGroups
		{
			get
			{
				return this._DOCUDocumentGroups;
			}
		}
		
	}
}
#pragma warning restore 1591
