#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using Excelsior.Domain;

namespace Excelsior.Domain	
{
	public partial class DOCU_DocumentGroup
	{
		private long _DocumentGroupID;
		public virtual long DocumentGroupID
		{
			get
			{
				return this._DocumentGroupID;
			}
			set
			{
				this._DocumentGroupID = value;
			}
		}
		
		private long? _DocuAuthorizationID;
		public virtual long? DocuAuthorizationID
		{
			get
			{
				return this._DocuAuthorizationID;
			}
			set
			{
				this._DocuAuthorizationID = value;
			}
		}
		
		private long? _TrialID;
		public virtual long? TrialID
		{
			get
			{
				return this._TrialID;
			}
			set
			{
				this._TrialID = value;
			}
		}
		
		private string _DocumentGroupDes;
		public virtual string DocumentGroupDes
		{
			get
			{
				return this._DocumentGroupDes;
			}
			set
			{
				this._DocumentGroupDes = value;
			}
		}
		
		private PACS_Trial _PACSTrial;
		public virtual PACS_Trial PACSTrial
		{
			get
			{
				return this._PACSTrial;
			}
			set
			{
				this._PACSTrial = value;
			}
		}
		
		private DOCU_AuthorizationType _DOCUAuthorizationType;
		public virtual DOCU_AuthorizationType DOCUAuthorizationType
		{
			get
			{
				return this._DOCUAuthorizationType;
			}
			set
			{
				this._DOCUAuthorizationType = value;
			}
		}
		
		private IList<DOCU_Document> _DOCUDocuments = new List<DOCU_Document>();
		public virtual IList<DOCU_Document> DOCU_Documents
		{
			get
			{
				return this._DOCUDocuments;
			}
		}
		
	}
}
#pragma warning restore 1591
