#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using Excelsior.Domain;

namespace Excelsior.Domain	
{
	public partial class DOCU_DocumentVersion
	{
		private long _DocumentVersionID;
		public virtual long DocumentVersionID
		{
			get
			{
				return this._DocumentVersionID;
			}
			set
			{
				this._DocumentVersionID = value;
			}
		}
		
		private string _DocumentVersion;
		public virtual string DocumentVersion
		{
			get
			{
				return this._DocumentVersion;
			}
			set
			{
				this._DocumentVersion = value;
			}
		}
		
		private string _FileLocation;
		public virtual string FileLocation
		{
			get
			{
				return this._FileLocation;
			}
			set
			{
				this._FileLocation = value;
			}
		}
		
		private long? _DocumentID;
		public virtual long? DocumentID
		{
			get
			{
				return this._DocumentID;
			}
			set
			{
				this._DocumentID = value;
			}
		}
		
		private bool _IsActive;
		public virtual bool IsActive
		{
			get
			{
				return this._IsActive;
			}
			set
			{
				this._IsActive = value;
			}
		}
		
		private string _RawFileLocation;
		public virtual string RawFileLocation
		{
			get
			{
				return this._RawFileLocation;
			}
			set
			{
				this._RawFileLocation = value;
			}
		}
		
		private string _AttachmentFileLocation;
		public virtual string AttachmentFileLocation
		{
			get
			{
				return this._AttachmentFileLocation;
			}
			set
			{
				this._AttachmentFileLocation = value;
			}
		}

        private long _StatusID;
        public virtual long StatusID
        {
            get
            {
                return this._StatusID;
            }
            set
            {
                this._StatusID = value;
            }
        }

        private long _AttachmentStatusID;
        public virtual long AttachmentStatusID
        {
            get
            {
                return this._AttachmentStatusID;
            }
            set
            {
                this._AttachmentStatusID = value;
            }
        }

        private string _LastError;
        public virtual string LastError
        {
            get
            {
                return this._LastError;
            }
            set
            {
                this._LastError = value;
            }
        }

        private bool _HasError;
        public virtual bool HasError
        {
            get
            {
                return this._HasError;
            }
            set
            {
                this._HasError = value;
            }
        }

        private string _AttachmentLastError;
        public virtual string AttachmentLastError
        {
            get
            {
                return this._AttachmentLastError;
            }
            set
            {
                this._AttachmentLastError = value;
            }
        }

        private bool _AttachmentHasError;
        public virtual bool AttachmentHasError
        {
            get
            {
                return this._AttachmentHasError;
            }
            set
            {
                this._AttachmentHasError = value;
            }
        }

        private DOCU_Document _DOCUDocument;
		public virtual DOCU_Document DOCUDocument
		{
			get
			{
				return this._DOCUDocument;
			}
			set
			{
				this._DOCUDocument = value;
			}
		}

        private PACS_RawDataStatus _UploadStatus;
        public virtual PACS_RawDataStatus UploadStatus
        {
            get
            {
                return this._UploadStatus;
            }
            set
            {
                this._UploadStatus = value;
            }
        }

        private PACS_RawDataStatus _AttachmentUploadStatus;
        public virtual PACS_RawDataStatus AttachmentUploadStatus
        {
            get
            {
                return this._AttachmentUploadStatus;
            }
            set
            {
                this._AttachmentUploadStatus = value;
            }
        }

        private IList<DOCU_DocumentVersionUser> _DOCUDocumentVersionUsers = new List<DOCU_DocumentVersionUser>();
		public virtual IList<DOCU_DocumentVersionUser> DOCU_DocumentVersionUsers
		{
			get
			{
				return this._DOCUDocumentVersionUsers;
			}
		}
		
	}
}
#pragma warning restore 1591
