#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using Excelsior.Domain;

namespace Excelsior.Domain	
{
	public partial class DOCU_Document
	{
		private long _DocumentID;
		public virtual long DocumentID
		{
			get
			{
				return this._DocumentID;
			}
			set
			{
				this._DocumentID = value;
			}
		}
		
		private bool _IsActive;
		public virtual bool IsActive
		{
			get
			{
				return this._IsActive;
			}
			set
			{
				this._IsActive = value;
			}
		}
		
		private int? _ReviewGracePeriodDays;
		public virtual int? ReviewGracePeriodDays
		{
			get
			{
				return this._ReviewGracePeriodDays;
			}
			set
			{
				this._ReviewGracePeriodDays = value;
			}
		}
		
		private int? _ReviewGoodUntilMonths;
		public virtual int? ReviewGoodUntilMonths
		{
			get
			{
				return this._ReviewGoodUntilMonths;
			}
			set
			{
				this._ReviewGoodUntilMonths = value;
			}
		}
		
		private string _DocumentName;
		public virtual string DocumentName
		{
			get
			{
				return this._DocumentName;
			}
			set
			{
				this._DocumentName = value;
			}
		}
		
		private long? _DocumentGroupID;
		public virtual long? DocumentGroupID
		{
			get
			{
				return this._DocumentGroupID;
			}
			set
			{
				this._DocumentGroupID = value;
			}
		}
		
		private DateTime? _ApprovalDate;
		public virtual DateTime? ApprovalDate
		{
			get
			{
				return this._ApprovalDate;
			}
			set
			{
				this._ApprovalDate = value;
			}
		}
		
		private int? _InternalAuditPeriodDays;
		public virtual int? InternalAuditPeriodDays
		{
			get
			{
				return this._InternalAuditPeriodDays;
			}
			set
			{
				this._InternalAuditPeriodDays = value;
			}
		}
		
		private int? _InternalAuditGoodUntilMonths;
		public virtual int? InternalAuditGoodUntilMonths
		{
			get
			{
				return this._InternalAuditGoodUntilMonths;
			}
			set
			{
				this._InternalAuditGoodUntilMonths = value;
			}
		}
		
		private DOCU_DocumentGroup _DOCUDocumentGroup;
		public virtual DOCU_DocumentGroup DOCUDocumentGroup
		{
			get
			{
				return this._DOCUDocumentGroup;
			}
			set
			{
				this._DOCUDocumentGroup = value;
			}
		}
		
		private IList<DOCU_DocumentVersion> _DOCUDocumentVersions = new List<DOCU_DocumentVersion>();
		public virtual IList<DOCU_DocumentVersion> DOCU_DocumentVersions
		{
			get
			{
				return this._DOCUDocumentVersions;
			}
		}
		
		private IList<DOCU_DocumentUser> _DOCUDocumentUsers = new List<DOCU_DocumentUser>();
		public virtual IList<DOCU_DocumentUser> DOCU_DocumentUsers
		{
			get
			{
				return this._DOCUDocumentUsers;
			}
		}

        private IList<DOCU_DocumentRole> _DOCUDocumentRoles = new List<DOCU_DocumentRole>();
        public virtual IList<DOCU_DocumentRole> DOCU_DocumentRoles
        {
            get
            {
                return this._DOCUDocumentRoles;
            }
        }
    }
}
#pragma warning restore 1591
