#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;

namespace Excelsior.Domain	
{
	public partial class EXCELSIOR_SYSTEM
	{
		private long _SystemID;
		public virtual long SystemID
		{
			get
			{
				return this._SystemID;
			}
			set
			{
				this._SystemID = value;
			}
		}
		
		private string _SystemVersion;
		public virtual string SystemVersion
		{
			get
			{
				return this._SystemVersion;
			}
			set
			{
				this._SystemVersion = value;
			}
		}
		
		private DateTime? _ScreenTimeOutInterval;
		public virtual DateTime? ScreenTimeOutInterval
		{
			get
			{
				return this._ScreenTimeOutInterval;
			}
			set
			{
				this._ScreenTimeOutInterval = value;
			}
		}
		
		private string _SystemType;
		public virtual string SystemType
		{
			get
			{
				return this._SystemType;
			}
			set
			{
				this._SystemType = value;
			}
		}
		
	}
}
#pragma warning restore 1591
