#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using Excelsior.Domain;

namespace Excelsior.Domain	
{
	public partial class GRD_GradingQuestion
	{
		private long _GQuestionID;
		public virtual long GQuestionID
		{
			get
			{
				return this._GQuestionID;
			}
			set
			{
				this._GQuestionID = value;
			}
		}
		
		private string _GQuestionDes;
		public virtual string GQuestionDes
		{
			get
			{
				return this._GQuestionDes;
			}
			set
			{
				this._GQuestionDes = value;
			}
		}
		
		private string _GQuestionString;
		public virtual string GQuestionString
		{
			get
			{
				return this._GQuestionString;
			}
			set
			{
				this._GQuestionString = value;
			}
		}
		
		private long? _GQuestionTagID;
		public virtual long? GQuestionTagID
		{
			get
			{
				return this._GQuestionTagID;
			}
			set
			{
				this._GQuestionTagID = value;
			}
		}
		
		private bool _IsAnswerMeasurement;
		public virtual bool IsAnswerMeasurement
		{
			get
			{
				return this._IsAnswerMeasurement;
			}
			set
			{
				this._IsAnswerMeasurement = value;
			}
		}
		
		private string _AnswerMask;
		public virtual string AnswerMask
		{
			get
			{
				return this._AnswerMask;
			}
			set
			{
				this._AnswerMask = value;
			}
		}
		
		private GRD_QuestionTag _GRDQuestionTag;
		public virtual GRD_QuestionTag GRDQuestionTag
		{
			get
			{
				return this._GRDQuestionTag;
			}
			set
			{
				this._GRDQuestionTag = value;
			}
		}
		
		private IList<GRD_GradingAnswer> _GRDGradingAnswers = new List<GRD_GradingAnswer>();
		public virtual IList<GRD_GradingAnswer> GRD_GradingAnswers
		{
			get
			{
				return this._GRDGradingAnswers;
			}
		}
		
		private IList<GRD_TempQuestion> _GRDTempQuestions = new List<GRD_TempQuestion>();
		public virtual IList<GRD_TempQuestion> GRD_TempQuestions
		{
			get
			{
				return this._GRDTempQuestions;
			}
		}
		
		private IList<GRD_Dependency> _GRDDependencies = new List<GRD_Dependency>();
		public virtual IList<GRD_Dependency> GRD_Dependencies
		{
			get
			{
				return this._GRDDependencies;
			}
		}
		
	}
}
#pragma warning restore 1591
