#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using Excelsior.Domain;

namespace Excelsior.Domain	
{
	public partial class GRD_QuestionGroup
	{
		private long _GQuestionGroupID;
		public virtual long GQuestionGroupID
		{
			get
			{
				return this._GQuestionGroupID;
			}
			set
			{
				this._GQuestionGroupID = value;
			}
		}
		
		private string _GQuestionGroupName;
		public virtual string GQuestionGroupName
		{
			get
			{
				return this._GQuestionGroupName;
			}
			set
			{
				this._GQuestionGroupName = value;
			}
		}
		
		private int? _GQuestionGroupSeq;
		public virtual int? GQuestionGroupSeq
		{
			get
			{
				return this._GQuestionGroupSeq;
			}
			set
			{
				this._GQuestionGroupSeq = value;
			}
		}
		
		private long? _GTemplateID;
		public virtual long? GTemplateID
		{
			get
			{
				return this._GTemplateID;
			}
			set
			{
				this._GTemplateID = value;
			}
		}
		
		private GRD_GradingTemplate _GRDGradingTemplate;
		public virtual GRD_GradingTemplate GRDGradingTemplate
		{
			get
			{
				return this._GRDGradingTemplate;
			}
			set
			{
				this._GRDGradingTemplate = value;
			}
		}
		
		private IList<GRD_TempQuestion> _GRDTempQuestions = new List<GRD_TempQuestion>();
		public virtual IList<GRD_TempQuestion> GRD_TempQuestions
		{
			get
			{
				return this._GRDTempQuestions;
			}
		}
		
	}
}
#pragma warning restore 1591
