#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using Excelsior.Domain;

namespace Excelsior.Domain	
{
	public partial class GRD_GradingTemplate
	{
		private long _GTemplateID;
		public virtual long GTemplateID
		{
			get
			{
				return this._GTemplateID;
			}
			set
			{
				this._GTemplateID = value;
			}
		}
		
		private string _GTemplateName;
		public virtual string GTemplateName
		{
			get
			{
				return this._GTemplateName;
			}
			set
			{
				this._GTemplateName = value;
			}
		}
		
		private string _GTemplateDes;
		public virtual string GTemplateDes
		{
			get
			{
				return this._GTemplateDes;
			}
			set
			{
				this._GTemplateDes = value;
			}
		}
		
		private long? _TrialID;
		public virtual long? TrialID
		{
			get
			{
				return this._TrialID;
			}
			set
			{
				this._TrialID = value;
			}
		}
		
		private bool _IsLocked;
		public virtual bool IsLocked
		{
			get
			{
				return this._IsLocked;
			}
			set
			{
				this._IsLocked = value;
			}
		}
		
		private bool _IsActive;
		public virtual bool IsActive
		{
			get
			{
				return this._IsActive;
			}
			set
			{
				this._IsActive = value;
			}
		}
		
		private PACS_Trial _PACSTrial;
		public virtual PACS_Trial PACSTrial
		{
			get
			{
				return this._PACSTrial;
			}
			set
			{
				this._PACSTrial = value;
			}
		}
		
		private IList<PACS_TPProcList> _PACSTPProcLists = new List<PACS_TPProcList>();
		public virtual IList<PACS_TPProcList> PACS_TPProcLists
		{
			get
			{
				return this._PACSTPProcLists;
			}
		}
		
		private IList<GRD_Report> _GRDReports = new List<GRD_Report>();
		public virtual IList<GRD_Report> GRD_Reports
		{
			get
			{
				return this._GRDReports;
			}
		}
		
		private IList<GRD_QuestionGroup> _GRDQuestionGroups = new List<GRD_QuestionGroup>();
		public virtual IList<GRD_QuestionGroup> GRD_QuestionGroups
		{
			get
			{
				return this._GRDQuestionGroups;
			}
		}
		
		private IList<PACS_SeriesGroup> _PACSSeriesGroups = new List<PACS_SeriesGroup>();
		public virtual IList<PACS_SeriesGroup> PACS_SeriesGroups
		{
			get
			{
				return this._PACSSeriesGroups;
			}
		}		
	}
}
#pragma warning restore 1591
