#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using Excelsior.Domain;

namespace Excelsior.Domain	
{
	public partial class GRD_Dependency
	{
		private long _GDependencyID;
		public virtual long GDependencyID
		{
			get
			{
				return this._GDependencyID;
			}
			set
			{
				this._GDependencyID = value;
			}
		}
		
		private long? _GSourceAnswerID;
		public virtual long? GSourceAnswerID
		{
			get
			{
				return this._GSourceAnswerID;
			}
			set
			{
				this._GSourceAnswerID = value;
			}
		}
		
		private long? _GTargetAnswerID;
		public virtual long? GTargetAnswerID
		{
			get
			{
				return this._GTargetAnswerID;
			}
			set
			{
				this._GTargetAnswerID = value;
			}
		}
		
		private long? _GTargetQuestionID;
		public virtual long? GTargetQuestionID
		{
			get
			{
				return this._GTargetQuestionID;
			}
			set
			{
				this._GTargetQuestionID = value;
			}
		}
		
		private bool _ActionEnable;
		public virtual bool ActionEnable
		{
			get
			{
				return this._ActionEnable;
			}
			set
			{
				this._ActionEnable = value;
			}
		}
		
		private GRD_GradingQuestion _GRDGradingQuestion;
		public virtual GRD_GradingQuestion GRDGradingQuestion
		{
			get
			{
				return this._GRDGradingQuestion;
			}
			set
			{
				this._GRDGradingQuestion = value;
			}
		}
		
		private GRD_GradingAnswer _GRDGradingAnswer;
		public virtual GRD_GradingAnswer GRDGradingAnswer
		{
			get
			{
				return this._GRDGradingAnswer;
			}
			set
			{
				this._GRDGradingAnswer = value;
			}
		}
		
		private GRD_GradingAnswer _GRDGradingAnswer1;
		public virtual GRD_GradingAnswer GRDGradingAnswer1
		{
			get
			{
				return this._GRDGradingAnswer1;
			}
			set
			{
				this._GRDGradingAnswer1 = value;
			}
		}
		
	}
}
#pragma warning restore 1591
