#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using Excelsior.Domain;

namespace Excelsior.Domain	
{
	public partial class GRD_GradingAnswer
	{
		private long _GAnswersID;
		public virtual long GAnswersID
		{
			get
			{
				return this._GAnswersID;
			}
			set
			{
				this._GAnswersID = value;
			}
		}
		
		private long? _GQuestionID;
		public virtual long? GQuestionID
		{
			get
			{
				return this._GQuestionID;
			}
			set
			{
				this._GQuestionID = value;
			}
		}
		
		private string _GAnswerString;
		public virtual string GAnswerString
		{
			get
			{
				return this._GAnswerString;
			}
			set
			{
				this._GAnswerString = value;
			}
		}
		
		private int? _GAnswerSeq;
		public virtual int? GAnswerSeq
		{
			get
			{
				return this._GAnswerSeq;
			}
			set
			{
				this._GAnswerSeq = value;
			}
		}
		
		private long? _TrialID;
		public virtual long? TrialID
		{
			get
			{
				return this._TrialID;
			}
			set
			{
				this._TrialID = value;
			}
		}
		
		private GRD_GradingQuestion _GRDGradingQuestion;
		public virtual GRD_GradingQuestion GRDGradingQuestion
		{
			get
			{
				return this._GRDGradingQuestion;
			}
			set
			{
				this._GRDGradingQuestion = value;
			}
		}
		
		private PACS_Trial _PACSTrial;
		public virtual PACS_Trial PACSTrial
		{
			get
			{
				return this._PACSTrial;
			}
			set
			{
				this._PACSTrial = value;
			}
		}
		
		private IList<GRD_Dependency> _GRDDependencies = new List<GRD_Dependency>();
		public virtual IList<GRD_Dependency> GRD_Dependencies
		{
			get
			{
				return this._GRDDependencies;
			}
		}
		
		private IList<GRD_Dependency> _GRDDependencies1 = new List<GRD_Dependency>();
		public virtual IList<GRD_Dependency> GRD_Dependencies1
		{
			get
			{
				return this._GRDDependencies1;
			}
		}
		
	}
}
#pragma warning restore 1591
