#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using Excelsior.Domain;

namespace Excelsior.Domain	
{
	public partial class GRD_ReportResult
	{
		private long _GRDReportResultID;
		public virtual long GRDReportResultID
		{
			get
			{
				return this._GRDReportResultID;
			}
			set
			{
				this._GRDReportResultID = value;
			}
		}
		
		private long? _GReportID;
		public virtual long? GReportID
		{
			get
			{
				return this._GReportID;
			}
			set
			{
				this._GReportID = value;
			}
		}
		
		private string _GQuestionString;
		public virtual string GQuestionString
		{
			get
			{
				return this._GQuestionString;
			}
			set
			{
				this._GQuestionString = value;
			}
		}
		
		private string _GQuestionGroupName;
		public virtual string GQuestionGroupName
		{
			get
			{
				return this._GQuestionGroupName;
			}
			set
			{
				this._GQuestionGroupName = value;
			}
		}
		
		private string _GQuestionDes;
		public virtual string GQuestionDes
		{
			get
			{
				return this._GQuestionDes;
			}
			set
			{
				this._GQuestionDes = value;
			}
		}
		
		private string _GAnswersString;
		public virtual string GAnswersString
		{
			get
			{
				return this._GAnswersString;
			}
			set
			{
				this._GAnswersString = value;
			}
		}
		
		private long? _GAnswerMeasurement;
		public virtual long? GAnswerMeasurement
		{
			get
			{
				return this._GAnswerMeasurement;
			}
			set
			{
				this._GAnswerMeasurement = value;
			}
		}
		
		private string _Laterality;
		public virtual string Laterality
		{
			get
			{
				return this._Laterality;
			}
			set
			{
				this._Laterality = value;
			}
		}
		
		private MEA_Measurement _MEAMeasurement;
		public virtual MEA_Measurement MEAMeasurement
		{
			get
			{
				return this._MEAMeasurement;
			}
			set
			{
				this._MEAMeasurement = value;
			}
		}
		
		private GRD_Report _GRDReport;
		public virtual GRD_Report GRDReport
		{
			get
			{
				return this._GRDReport;
			}
			set
			{
				this._GRDReport = value;
			}
		}
		
	}
}
#pragma warning restore 1591
