#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using Excelsior.Domain;

namespace Excelsior.Domain	
{
	public partial class GRD_Report
	{
		private long _GReportID;
		public virtual long GReportID
		{
			get
			{
				return this._GReportID;
			}
			set
			{
				this._GReportID = value;
			}
		}
		
		private long? _PerformedBy;
		public virtual long? PerformedBy
		{
			get
			{
				return this._PerformedBy;
			}
			set
			{
				this._PerformedBy = value;
			}
		}
		
		private bool _IsPrimaryResult;
		public virtual bool IsPrimaryResult
		{
			get
			{
				return this._IsPrimaryResult;
			}
			set
			{
				this._IsPrimaryResult = value;
			}
		}
		
		private bool _IsActive;
		public virtual bool IsActive
		{
			get
			{
				return this._IsActive;
			}
			set
			{
				this._IsActive = value;
			}
		}
		
		private DateTime? _PerformedDate;
		public virtual DateTime? PerformedDate
		{
			get
			{
				return this._PerformedDate;
			}
			set
			{
				this._PerformedDate = value;
			}
		}
		
		private DateTime? _PerformedTime;
		public virtual DateTime? PerformedTime
		{
			get
			{
				return this._PerformedTime;
			}
			set
			{
				this._PerformedTime = value;
			}
		}
		
		private long? _SeriesID;
		public virtual long? SeriesID
		{
			get
			{
				return this._SeriesID;
			}
			set
			{
				this._SeriesID = value;
			}
		}
		
		private long? _GTemplateID;
		public virtual long? GTemplateID
		{
			get
			{
				return this._GTemplateID;
			}
			set
			{
				this._GTemplateID = value;
			}
		}
		
		private bool _IsSigned;
		public virtual bool IsSigned
		{
			get
			{
				return this._IsSigned;
			}
			set
			{
				this._IsSigned = value;
			}
		}
		
		private PACS_Series _PACSSeries;
		public virtual PACS_Series PACSSeries
		{
			get
			{
				return this._PACSSeries;
			}
			set
			{
				this._PACSSeries = value;
			}
		}
		
		private CONTACT_User _CONTACTUser;
		public virtual CONTACT_User CONTACTUser
		{
			get
			{
				return this._CONTACTUser;
			}
			set
			{
				this._CONTACTUser = value;
			}
		}
		
		private GRD_GradingTemplate _GRDGradingTemplate;
		public virtual GRD_GradingTemplate GRDGradingTemplate
		{
			get
			{
				return this._GRDGradingTemplate;
			}
			set
			{
				this._GRDGradingTemplate = value;
			}
		}
		
		private IList<GRD_ReportResult> _GRDReportResults = new List<GRD_ReportResult>();
		public virtual IList<GRD_ReportResult> GRD_ReportResults
		{
			get
			{
				return this._GRDReportResults;
			}
		}
		
		private IList<MEA_Measurement> _MEAMeasurements = new List<MEA_Measurement>();
		public virtual IList<MEA_Measurement> MEA_Measurements
		{
			get
			{
				return this._MEAMeasurements;
			}
		}

        private IList<PACS_SeriesAttachment> _PACSSeriesAttachments = new List<PACS_SeriesAttachment>();
        public virtual IList<PACS_SeriesAttachment> PACS_SeriesAttachments
        {
            get
            {
                return this._PACSSeriesAttachments;
            }
        }
    }
}
#pragma warning restore 1591
