#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using Excelsior.Domain;

namespace Excelsior.Domain	
{
	public partial class GRD_Impression
	{
		private long _ImpressionID;
		public virtual long ImpressionID
		{
			get
			{
				return this._ImpressionID;
			}
			set
			{
				this._ImpressionID = value;
			}
		}
		
		private string _ImpressionDes;
		public virtual string ImpressionDes
		{
			get
			{
				return this._ImpressionDes;
			}
			set
			{
				this._ImpressionDes = value;
			}
		}
		
		private string _ImpressionColor;
		public virtual string ImpressionColor
		{
			get
			{
				return this._ImpressionColor;
			}
			set
			{
				this._ImpressionColor = value;
			}
		}
		
		private IList<PACS_Trial> _PACSTrials = new List<PACS_Trial>();
		public virtual IList<PACS_Trial> PACS_Trials
		{
			get
			{
				return this._PACSTrials;
			}
		}
		
	}
}
#pragma warning restore 1591
