#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using Excelsior.Domain;

namespace Excelsior.Domain	
{
	public partial class MEA_OCTLayer : MEA_Measurement
	{
		private string _LayerLabel;
		public virtual string LayerLabel
		{
			get
			{
				return this._LayerLabel;
			}
			set
			{
				this._LayerLabel = value;
			}
		}
		
		private string _MeasurementXML;
		public virtual string MeasurementXML
		{
			get
			{
				return this._MeasurementXML;
			}
			set
			{
				this._MeasurementXML = value;
			}
		}
		
	}
}
#pragma warning restore 1591
