#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using Excelsior.Domain;

namespace Excelsior.Domain	
{
	public partial class MEA_Freehand : MEA_Measurement
	{
		private string _MeasurementXML;
		public virtual string MeasurementXML
		{
			get
			{
				return this._MeasurementXML;
			}
			set
			{
				this._MeasurementXML = value;
			}
		}
		
		private string _Tag;
		public virtual string Tag
		{
			get
			{
				return this._Tag;
			}
			set
			{
				this._Tag = value;
			}
		}
		
		private string _Color;
		public virtual string Color
		{
			get
			{
				return this._Color;
			}
			set
			{
				this._Color = value;
			}
		}
		
	}
}
#pragma warning restore 1591
