#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using Excelsior.Domain;

namespace Excelsior.Domain	
{
	public partial class MEA_MeasDataType
	{
		private long _MeasDataTypeID;
		public virtual long MeasDataTypeID
		{
			get
			{
				return this._MeasDataTypeID;
			}
			set
			{
				this._MeasDataTypeID = value;
			}
		}
		
		private long? _DataTypeID;
		public virtual long? DataTypeID
		{
			get
			{
				return this._DataTypeID;
			}
			set
			{
				this._DataTypeID = value;
			}
		}
		
		private long? _MeasurementTypeID;
		public virtual long? MeasurementTypeID
		{
			get
			{
				return this._MeasurementTypeID;
			}
			set
			{
				this._MeasurementTypeID = value;
			}
		}
		
		private PACS_DataType _PACSDataType;
		public virtual PACS_DataType PACSDataType
		{
			get
			{
				return this._PACSDataType;
			}
			set
			{
				this._PACSDataType = value;
			}
		}
		
		private MEA_MeasurementType _MEAMeasurementType;
		public virtual MEA_MeasurementType MEAMeasurementType
		{
			get
			{
				return this._MEAMeasurementType;
			}
			set
			{
				this._MEAMeasurementType = value;
			}
		}
		
	}
}
#pragma warning restore 1591
