#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using Excelsior.Domain;

namespace Excelsior.Domain	
{
	public partial class MEA_Distance : MEA_Measurement
	{
		private double? _DistanceMm;
		public virtual double? DistanceMm
		{
			get
			{
				return this._DistanceMm;
			}
			set
			{
				this._DistanceMm = value;
			}
		}
		
		private double? _StartX;
		public virtual double? StartX
		{
			get
			{
				return this._StartX;
			}
			set
			{
				this._StartX = value;
			}
		}
		
		private double? _StartY;
		public virtual double? StartY
		{
			get
			{
				return this._StartY;
			}
			set
			{
				this._StartY = value;
			}
		}
		
		private double? _EndX;
		public virtual double? EndX
		{
			get
			{
				return this._EndX;
			}
			set
			{
				this._EndX = value;
			}
		}
		
		private double? _EndY;
		public virtual double? EndY
		{
			get
			{
				return this._EndY;
			}
			set
			{
				this._EndY = value;
			}
		}
		
	}
}
#pragma warning restore 1591
