#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Excelsior.Domain	
{
	public partial class MEA_Stencil
    {
		private long _StencilID;
		public virtual long StencilID
		{
			get
			{
				return this._StencilID;
			}
			set
			{
				this._StencilID = value;
			}
		}
		
		private long? _TrialID;
		public virtual long? TrialID
        {
			get
			{
				return this._TrialID;
			}
			set
			{
				this._TrialID = value;
			}
		}

        private string _Tag;
        public virtual string Tag
        {
            get
            {
                return this._Tag;
            }
            set
            {
                this._Tag = value;
            }
        }

        private string _Color;
        public virtual string Color
        {
            get
            {
                return this._Color;
            }
            set
            {
                this._Color = value;
            }
        }

        private PACS_Trial _PACSTrial;
        public virtual PACS_Trial PACSTrial
        {
            get
            {
                return this._PACSTrial;
            }
            set
            {
                this._PACSTrial = value;
            }
        }
    }
}
#pragma warning restore 1591
