#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using Excelsior.Domain;

namespace Excelsior.Domain	
{
	public partial class MEA_OCTGrid : MEA_Measurement
	{
		private string _OCTGridLabel;
		public virtual string OCTGridLabel
		{
			get
			{
				return this._OCTGridLabel;
			}
			set
			{
				this._OCTGridLabel = value;
			}
		}
		
		private double? _CenterPointThicknessMm;
		public virtual double? CenterPointThicknessMm
		{
			get
			{
				return this._CenterPointThicknessMm;
			}
			set
			{
				this._CenterPointThicknessMm = value;
			}
		}
		
		private double? _TotalVolumeMm3;
		public virtual double? TotalVolumeMm3
		{
			get
			{
				return this._TotalVolumeMm3;
			}
			set
			{
				this._TotalVolumeMm3 = value;
			}
		}
		
		private double? _Sector0Thick;
		public virtual double? Sector0Thick
		{
			get
			{
				return this._Sector0Thick;
			}
			set
			{
				this._Sector0Thick = value;
			}
		}
		
		private double? _Sector1Thick;
		public virtual double? Sector1Thick
		{
			get
			{
				return this._Sector1Thick;
			}
			set
			{
				this._Sector1Thick = value;
			}
		}
		
		private double? _Sector2Thick;
		public virtual double? Sector2Thick
		{
			get
			{
				return this._Sector2Thick;
			}
			set
			{
				this._Sector2Thick = value;
			}
		}
		
		private double? _Sector3Thick;
		public virtual double? Sector3Thick
		{
			get
			{
				return this._Sector3Thick;
			}
			set
			{
				this._Sector3Thick = value;
			}
		}
		
		private double? _Sector4Thick;
		public virtual double? Sector4Thick
		{
			get
			{
				return this._Sector4Thick;
			}
			set
			{
				this._Sector4Thick = value;
			}
		}
		
		private double? _Sector5Thick;
		public virtual double? Sector5Thick
		{
			get
			{
				return this._Sector5Thick;
			}
			set
			{
				this._Sector5Thick = value;
			}
		}
		
		private double? _Sector6Thick;
		public virtual double? Sector6Thick
		{
			get
			{
				return this._Sector6Thick;
			}
			set
			{
				this._Sector6Thick = value;
			}
		}
		
		private double? _Sector7Thick;
		public virtual double? Sector7Thick
		{
			get
			{
				return this._Sector7Thick;
			}
			set
			{
				this._Sector7Thick = value;
			}
		}
		
		private double? _Sector8Thick;
		public virtual double? Sector8Thick
		{
			get
			{
				return this._Sector8Thick;
			}
			set
			{
				this._Sector8Thick = value;
			}
		}
		
		private double? _Sector0Vol;
		public virtual double? Sector0Vol
		{
			get
			{
				return this._Sector0Vol;
			}
			set
			{
				this._Sector0Vol = value;
			}
		}
		
		private double? _Sector1Vol;
		public virtual double? Sector1Vol
		{
			get
			{
				return this._Sector1Vol;
			}
			set
			{
				this._Sector1Vol = value;
			}
		}
		
		private double? _Sector2Vol;
		public virtual double? Sector2Vol
		{
			get
			{
				return this._Sector2Vol;
			}
			set
			{
				this._Sector2Vol = value;
			}
		}
		
		private double? _Sector3Vol;
		public virtual double? Sector3Vol
		{
			get
			{
				return this._Sector3Vol;
			}
			set
			{
				this._Sector3Vol = value;
			}
		}
		
		private double? _Sector4Vol;
		public virtual double? Sector4Vol
		{
			get
			{
				return this._Sector4Vol;
			}
			set
			{
				this._Sector4Vol = value;
			}
		}
		
		private double? _Sector5Vol;
		public virtual double? Sector5Vol
		{
			get
			{
				return this._Sector5Vol;
			}
			set
			{
				this._Sector5Vol = value;
			}
		}
		
		private double? _Sector6Vol;
		public virtual double? Sector6Vol
		{
			get
			{
				return this._Sector6Vol;
			}
			set
			{
				this._Sector6Vol = value;
			}
		}
		
		private double? _Sector7Vol;
		public virtual double? Sector7Vol
		{
			get
			{
				return this._Sector7Vol;
			}
			set
			{
				this._Sector7Vol = value;
			}
		}
		
		private double? _Sector8Vol;
		public virtual double? Sector8Vol
		{
			get
			{
				return this._Sector8Vol;
			}
			set
			{
				this._Sector8Vol = value;
			}
		}
		
		private double? _CenterLocationFrame;
		public virtual double? CenterLocationFrame
		{
			get
			{
				return this._CenterLocationFrame;
			}
			set
			{
				this._CenterLocationFrame = value;
			}
		}
		
		private double? _CenterLocationAscan;
		public virtual double? CenterLocationAscan
		{
			get
			{
				return this._CenterLocationAscan;
			}
			set
			{
				this._CenterLocationAscan = value;
			}
		}
		
		private string _OCTGridLayer2;
		public virtual string OCTGridLayer2
		{
			get
			{
				return this._OCTGridLayer2;
			}
			set
			{
				this._OCTGridLayer2 = value;
			}
		}
		
		private string _OCTGridLayer1;
		public virtual string OCTGridLayer1
		{
			get
			{
				return this._OCTGridLayer1;
			}
			set
			{
				this._OCTGridLayer1 = value;
			}
		}
		
	}
}
#pragma warning restore 1591
