#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using Excelsior.Domain;

namespace Excelsior.Domain	
{
	public partial class MEA_ETDRSGrid : MEA_Measurement
	{
		private double? _FoveaLocationX;
		public virtual double? FoveaLocationX
		{
			get
			{
				return this._FoveaLocationX;
			}
			set
			{
				this._FoveaLocationX = value;
			}
		}
		
		private double? _FoveaLocationY;
		public virtual double? FoveaLocationY
		{
			get
			{
				return this._FoveaLocationY;
			}
			set
			{
				this._FoveaLocationY = value;
			}
		}
		
		private double? _ONHLocationX;
		public virtual double? ONHLocationX
		{
			get
			{
				return this._ONHLocationX;
			}
			set
			{
				this._ONHLocationX = value;
			}
		}
		
		private double? _ONHLocationY;
		public virtual double? ONHLocationY
		{
			get
			{
				return this._ONHLocationY;
			}
			set
			{
				this._ONHLocationY = value;
			}
		}
		
		private double? _Sector0;
		public virtual double? Sector0
		{
			get
			{
				return this._Sector0;
			}
			set
			{
				this._Sector0 = value;
			}
		}
		
		private double? _Sector1;
		public virtual double? Sector1
		{
			get
			{
				return this._Sector1;
			}
			set
			{
				this._Sector1 = value;
			}
		}
		
		private double? _Sector2;
		public virtual double? Sector2
		{
			get
			{
				return this._Sector2;
			}
			set
			{
				this._Sector2 = value;
			}
		}
		
		private double? _Sector3;
		public virtual double? Sector3
		{
			get
			{
				return this._Sector3;
			}
			set
			{
				this._Sector3 = value;
			}
		}
		
		private double? _Sector4;
		public virtual double? Sector4
		{
			get
			{
				return this._Sector4;
			}
			set
			{
				this._Sector4 = value;
			}
		}
		
		private double? _Sector5;
		public virtual double? Sector5
		{
			get
			{
				return this._Sector5;
			}
			set
			{
				this._Sector5 = value;
			}
		}
		
		private double? _Sector6;
		public virtual double? Sector6
		{
			get
			{
				return this._Sector6;
			}
			set
			{
				this._Sector6 = value;
			}
		}
		
		private double? _Sector7;
		public virtual double? Sector7
		{
			get
			{
				return this._Sector7;
			}
			set
			{
				this._Sector7 = value;
			}
		}
		
		private double? _Sector8;
		public virtual double? Sector8
		{
			get
			{
				return this._Sector8;
			}
			set
			{
				this._Sector8 = value;
			}
		}
		
	}
}
#pragma warning restore 1591
