#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using Excelsior.Domain;

namespace Excelsior.Domain	
{
	public partial class MEA_Area : MEA_Measurement
	{
		private double? _AreaSizeMm2;
		public virtual double? AreaSizeMm2
		{
			get
			{
				return this._AreaSizeMm2;
			}
			set
			{
				this._AreaSizeMm2 = value;
			}
		}
		
		private double? _AreaSizeDA;
		public virtual double? AreaSizeDA
		{
			get
			{
				return this._AreaSizeDA;
			}
			set
			{
				this._AreaSizeDA = value;
			}
		}
		
		private double? _DistanceToFoveaMm;
		public virtual double? DistanceToFoveaMm
		{
			get
			{
				return this._DistanceToFoveaMm;
			}
			set
			{
				this._DistanceToFoveaMm = value;
			}
		}
		
		private double? _PerimeterMm;
		public virtual double? PerimeterMm
		{
			get
			{
				return this._PerimeterMm;
			}
			set
			{
				this._PerimeterMm = value;
			}
		}
		
		private string _AreaLabel;
		public virtual string AreaLabel
		{
			get
			{
				return this._AreaLabel;
			}
			set
			{
				this._AreaLabel = value;
			}
		}
		
		private string _MeasurementXML;
		public virtual string MeasurementXML
		{
			get
			{
				return this._MeasurementXML;
			}
			set
			{
				this._MeasurementXML = value;
			}
		}
		
	}
}
#pragma warning restore 1591
