#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using Excelsior.Domain;

namespace Excelsior.Domain	
{
	public partial class MEA_Measurement
	{
		private long _MeasurementID;
		public virtual long MeasurementID
		{
			get
			{
				return this._MeasurementID;
			}
			set
			{
				this._MeasurementID = value;
			}
		}
		
		private long? _GReportID;
		public virtual long? GReportID
		{
			get
			{
				return this._GReportID;
			}
			set
			{
				this._GReportID = value;
			}
		}
		
		private long? _MeasurementTypeID;
		public virtual long? MeasurementTypeID
		{
			get
			{
				return this._MeasurementTypeID;
			}
			set
			{
				this._MeasurementTypeID = value;
			}
		}
		
		private long? _DicomFrameID;
		public virtual long? DicomFrameID
		{
			get
			{
				return this._DicomFrameID;
			}
			set
			{
				this._DicomFrameID = value;
			}
		}
		
		private long? _RawDataID;
		public virtual long? RawDataID
		{
			get
			{
				return this._RawDataID;
			}
			set
			{
				this._RawDataID = value;
			}
		}
		
		private PACS_RawDatum _PACSRawDatum;
		public virtual PACS_RawDatum PACSRawDatum
		{
			get
			{
				return this._PACSRawDatum;
			}
			set
			{
				this._PACSRawDatum = value;
			}
		}
		
		private PACS_DicomFrame _PACSDicomFrame;
		public virtual PACS_DicomFrame PACSDicomFrame
		{
			get
			{
				return this._PACSDicomFrame;
			}
			set
			{
				this._PACSDicomFrame = value;
			}
		}
		
		private MEA_MeasurementType _MEAMeasurementType;
		public virtual MEA_MeasurementType MEAMeasurementType
		{
			get
			{
				return this._MEAMeasurementType;
			}
			set
			{
				this._MEAMeasurementType = value;
			}
		}
		
		private GRD_Report _GRDReport;
		public virtual GRD_Report GRDReport
		{
			get
			{
				return this._GRDReport;
			}
			set
			{
				this._GRDReport = value;
			}
		}
		
		private IList<GRD_ReportResult> _GRDReportResults = new List<GRD_ReportResult>();
		public virtual IList<GRD_ReportResult> GRD_ReportResults
		{
			get
			{
				return this._GRDReportResults;
			}
		}

        private IList<CRF_DataResult> _CRFDataResults = new List<CRF_DataResult>();
        public virtual IList<CRF_DataResult> CRF_DataResults
        {
            get
            {
                return this._CRFDataResults;
            }
        }
    }
}
#pragma warning restore 1591
