#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using Excelsior.Domain;

namespace Excelsior.Domain	
{
	public partial class MEA_MeasurementType
	{
		private long _MeasurementTypeID;
		public virtual long MeasurementTypeID
		{
			get
			{
				return this._MeasurementTypeID;
			}
			set
			{
				this._MeasurementTypeID = value;
			}
		}
		
		private string _MeasurementType;
		public virtual string MeasurementType
		{
			get
			{
				return this._MeasurementType;
			}
			set
			{
				this._MeasurementType = value;
			}
		}
		
		private IList<MEA_MeasDataType> _MEAMeasDataTypes = new List<MEA_MeasDataType>();
		public virtual IList<MEA_MeasDataType> MEA_MeasDataTypes
		{
			get
			{
				return this._MEAMeasDataTypes;
			}
		}
		
		private IList<MEA_Measurement> _MEAMeasurements = new List<MEA_Measurement>();
		public virtual IList<MEA_Measurement> MEA_Measurements
		{
			get
			{
				return this._MEAMeasurements;
			}
		}
		
	}
}
#pragma warning restore 1591
