#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using Excelsior.Domain;

namespace Excelsior.Domain	
{
	public partial class PACS_RawDataStatus
	{
		private long _StatusID;
		public virtual long StatusID
		{
			get
			{
				return this._StatusID;
			}
			set
			{
				this._StatusID = value;
			}
		}
		
		private string _StatusName;
		public virtual string StatusName
		{
			get
			{
				return this._StatusName;
			}
			set
			{
				this._StatusName = value;
			}
		}		
    }
}
#pragma warning restore 1591
