#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using Excelsior.Domain;

namespace Excelsior.Domain	
{
	public partial class PACS_DicomFrame
	{
		private long? _RawDataID;
		public virtual long? RawDataID
		{
			get
			{
				return this._RawDataID;
			}
			set
			{
				this._RawDataID = value;
			}
		}
		
		private int? _ImageWidth;
		public virtual int? ImageWidth
		{
			get
			{
				return this._ImageWidth;
			}
			set
			{
				this._ImageWidth = value;
			}
		}
		
		private int? _ImageHeight;
		public virtual int? ImageHeight
		{
			get
			{
				return this._ImageHeight;
			}
			set
			{
				this._ImageHeight = value;
			}
		}
		
		private int? _FrameIndex;
		public virtual int? FrameIndex
		{
			get
			{
				return this._FrameIndex;
			}
			set
			{
				this._FrameIndex = value;
			}
		}
		
		private string _FrameImageLocation;
		public virtual string FrameImageLocation
		{
			get
			{
				return this._FrameImageLocation;
			}
			set
			{
				this._FrameImageLocation = value;
			}
		}
		
		private long _DicomFrameID;
		public virtual long DicomFrameID
		{
			get
			{
				return this._DicomFrameID;
			}
			set
			{
				this._DicomFrameID = value;
			}
		}
		
		private bool _IsActive;
		public virtual bool IsActive
		{
			get
			{
				return this._IsActive;
			}
			set
			{
				this._IsActive = value;
			}
		}
		
		private string _RefLineType;
		public virtual string RefLineType
		{
			get
			{
				return this._RefLineType;
			}
			set
			{
				this._RefLineType = value;
			}
		}
		
		private string _RefLineCoordinates;
		public virtual string RefLineCoordinates
		{
			get
			{
				return this._RefLineCoordinates;
			}
			set
			{
				this._RefLineCoordinates = value;
			}
		}
		
		private bool _IsKeyFrame;
		public virtual bool IsKeyFrame
		{
			get
			{
				return this._IsKeyFrame;
			}
			set
			{
				this._IsKeyFrame = value;
			}
		}
		
		private PACS_RawDatum _PACSRawDatum;
		public virtual PACS_RawDatum PACSRawDatum
		{
			get
			{
				return this._PACSRawDatum;
			}
			set
			{
				this._PACSRawDatum = value;
			}
		}
		
		private IList<MEA_Measurement> _MEAMeasurements = new List<MEA_Measurement>();
		public virtual IList<MEA_Measurement> MEA_Measurements
		{
			get
			{
				return this._MEAMeasurements;
			}
		}
		
		private IList<PACS_ProcessedDatum> _PACSProcessedData = new List<PACS_ProcessedDatum>();
		public virtual IList<PACS_ProcessedDatum> PACS_ProcessedData
		{
			get
			{
				return this._PACSProcessedData;
			}
		}
		
	}
}
#pragma warning restore 1591
