#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using Excelsior.Domain;

namespace Excelsior.Domain
{
    public partial class PACS_Trial
    {
        private DateTime? _TrialStartDate;
        public virtual DateTime? TrialStartDate
        {
            get
            {
                return this._TrialStartDate;
            }
            set
            {
                this._TrialStartDate = value;
            }
        }

        private string _TrialPhase;
        public virtual string TrialPhase
        {
            get
            {
                return this._TrialPhase;
            }
            set
            {
                this._TrialPhase = value;
            }
        }

        private string _TrialName;
        public virtual string TrialName
        {
            get
            {
                return this._TrialName;
            }
            set
            {
                this._TrialName = value;
            }
        }

        private string _TrialLocations;
        public virtual string TrialLocations
        {
            get
            {
                return this._TrialLocations;
            }
            set
            {
                this._TrialLocations = value;
            }
        }

        private long _TrialID;
        public virtual long TrialID
        {
            get
            {
                return this._TrialID;
            }
            set
            {
                this._TrialID = value;
            }
        }

        private DateTime? _TrialEndDate;
        public virtual DateTime? TrialEndDate
        {
            get
            {
                return this._TrialEndDate;
            }
            set
            {
                this._TrialEndDate = value;
            }
        }

        private string _TrialArm;
        public virtual string TrialArm
        {
            get
            {
                return this._TrialArm;
            }
            set
            {
                this._TrialArm = value;
            }
        }

        private string _TrialAlias;
        public virtual string TrialAlias
        {
            get
            {
                return this._TrialAlias;
            }
            set
            {
                this._TrialAlias = value;
            }
        }

        private string _TherapeuticClass;
        public virtual string TherapeuticClass
        {
            get
            {
                return this._TherapeuticClass;
            }
            set
            {
                this._TherapeuticClass = value;
            }
        }

        private string _ProtocolTitle;
        public virtual string ProtocolTitle
        {
            get
            {
                return this._ProtocolTitle;
            }
            set
            {
                this._ProtocolTitle = value;
            }
        }

        private string _PrimaryDrugs;
        public virtual string PrimaryDrugs
        {
            get
            {
                return this._PrimaryDrugs;
            }
            set
            {
                this._PrimaryDrugs = value;
            }
        }

        private string _OtherDrugs;
        public virtual string OtherDrugs
        {
            get
            {
                return this._OtherDrugs;
            }
            set
            {
                this._OtherDrugs = value;
            }
        }

        private bool _NeedCertification;
        public virtual bool NeedCertification
        {
            get
            {
                return this._NeedCertification;
            }
            set
            {
                this._NeedCertification = value;
            }
        }

        private DateTime? _LastSubjectVisitDate;
        public virtual DateTime? LastSubjectVisitDate
        {
            get
            {
                return this._LastSubjectVisitDate;
            }
            set
            {
                this._LastSubjectVisitDate = value;
            }
        }

        private DateTime? _LastSubjectEnrollDate;
        public virtual DateTime? LastSubjectEnrollDate
        {
            get
            {
                return this._LastSubjectEnrollDate;
            }
            set
            {
                this._LastSubjectEnrollDate = value;
            }
        }

        private DateTime? _LastDataExportDate;
        public virtual DateTime? LastDataExportDate
        {
            get
            {
                return this._LastDataExportDate;
            }
            set
            {
                this._LastDataExportDate = value;
            }
        }

        private bool _IsValidated;
        public virtual bool IsValidated
        {
            get
            {
                return this._IsValidated;
            }
            set
            {
                this._IsValidated = value;
            }
        }

        private bool _IsActive;
        public virtual bool IsActive
        {
            get
            {
                return this._IsActive;
            }
            set
            {
                this._IsActive = value;
            }
        }

        private DateTime? _FirstSubjectEnrollDate;
        public virtual DateTime? FirstSubjectEnrollDate
        {
            get
            {
                return this._FirstSubjectEnrollDate;
            }
            set
            {
                this._FirstSubjectEnrollDate = value;
            }
        }

        private DateTime? _FirstDataExportDate;
        public virtual DateTime? FirstDataExportDate
        {
            get
            {
                return this._FirstDataExportDate;
            }
            set
            {
                this._FirstDataExportDate = value;
            }
        }

        private string _DiseaseType;
        public virtual string DiseaseType
        {
            get
            {
                return this._DiseaseType;
            }
            set
            {
                this._DiseaseType = value;
            }
        }

        private bool _IsEligibilityIDUsed;
        public virtual bool IsEligibilityIDUsed
        {
            get
            {
                return this._IsEligibilityIDUsed;
            }
            set
            {
                this._IsEligibilityIDUsed = value;
            }
        }

        private bool _IsCompletedPublic;
        public virtual bool IsCompletedPublic
        {
            get
            {
                return this._IsCompletedPublic;
            }
            set
            {
                this._IsCompletedPublic = value;
            }
        }

        private string _SubjectSeg;
        public virtual string SubjectSeg
        {
            get
            {
                return this._SubjectSeg;
            }
            set
            {
                this._SubjectSeg = value;
            }
        }

        private bool _IsSubjectNameCodeRequired;
        public virtual bool IsSubjectNameCodeRequired
        {
            get
            {
                return this._IsSubjectNameCodeRequired;
            }
            set
            {
                this._IsSubjectNameCodeRequired = value;
            }
        }

        private bool _IsLocked;
        public virtual bool IsLocked
        {
            get
            {
                return this._IsLocked;
            }
            set
            {
                this._IsLocked = value;
            }
        }

        private bool _IsTestingPhase;
        public virtual bool IsTestingPhase
        {
            get
            {
                return this._IsTestingPhase;
            }
            set
            {
                this._IsTestingPhase = value;
            }
        }

        private bool _IsEligibilityCloningEnabled;
        public virtual bool IsEligibilityCloningEnabled
        {
            get
            {
                return this._IsEligibilityCloningEnabled;
            }
            set
            {
                this._IsEligibilityCloningEnabled = value;
            }
        }

        private bool _ShouldEligibleLateralityBeDetermined;
        public virtual bool ShouldEligibleLateralityBeDetermined
        {
            get
            {
                return this._ShouldEligibleLateralityBeDetermined;
            }
            set
            {
                this._ShouldEligibleLateralityBeDetermined = value;
            }
        }

        private bool _IsSubjectGenderRequired;
        public virtual bool IsSubjectGenderRequired
        {
            get
            {
                return this._IsSubjectGenderRequired;
            }
            set
            {
                this._IsSubjectGenderRequired = value;
            }
        }

        private string _SubjectNameCodeMask;
        public virtual string SubjectNameCodeMask
        {
            get
            {
                return this._SubjectNameCodeMask;
            }
            set
            {
                this._SubjectNameCodeMask = value;
            }
        }

        private string _SubjectIDMask;
        public virtual string SubjectIDMask
        {
            get
            {
                return this._SubjectIDMask;
            }
            set
            {
                this._SubjectIDMask = value;
            }
        }

        private string _SubjectAlternativeIDMask;
        public virtual string SubjectAlternativeIDMask
        {
            get
            {
                return this._SubjectAlternativeIDMask;
            }
            set
            {
                this._SubjectAlternativeIDMask = value;
            }
        }

        private bool _IsSubjectBirthYearRequired;
        public virtual bool IsSubjectBirthYearRequired
        {
            get
            {
                return this._IsSubjectBirthYearRequired;
            }
            set
            {
                this._IsSubjectBirthYearRequired = value;
            }
        }

        private long? _AnimalSpeciesID;
        public virtual long? AnimalSpeciesID
        {
            get
            {
                return this._AnimalSpeciesID;
            }
            set
            {
                this._AnimalSpeciesID = value;
            }
        }

        private long? _ImpressionID;
        public virtual long? ImpressionID
        {
            get
            {
                return this._ImpressionID;
            }
            set
            {
                this._ImpressionID = value;
            }
        }

        private DateTime? _TrialLockedDate;
        public virtual DateTime? TrialLockedDate
        {
            get
            {
                return this._TrialLockedDate;
            }
            set
            {
                this._TrialLockedDate = value;
            }
        }

        private bool _AlwaysVerifyMultipleGrades;
        public virtual bool AlwaysVerifyMultipleGrades
        {
            get
            {
                return this._AlwaysVerifyMultipleGrades;
            }
            set
            {
                this._AlwaysVerifyMultipleGrades = value;
            }
        }

        private bool _IsHostBothLaterality;
        public virtual bool IsHostBothLaterality
        {
            get
            {
                return this._IsHostBothLaterality;
            }
            set
            {
                this._IsHostBothLaterality = value;
            }
        }

        private CFG_AnimalSpecy _CFGAnimalSpecy;
        public virtual CFG_AnimalSpecy CFGAnimalSpecy
        {
            get
            {
                return this._CFGAnimalSpecy;
            }
            set
            {
                this._CFGAnimalSpecy = value;
            }
        }

        private GRD_Impression _GRDImpression;
        public virtual GRD_Impression GRDImpression
        {
            get
            {
                return this._GRDImpression;
            }
            set
            {
                this._GRDImpression = value;
            }
        }

        private IList<PACS_TimePointsList> _PACSTimePointsLists = new List<PACS_TimePointsList>();
        public virtual IList<PACS_TimePointsList> PACS_TimePointsLists
        {
            get
            {
                return this._PACSTimePointsLists;
            }
        }

        private IList<PACS_Site> _PACSSites = new List<PACS_Site>();
        public virtual IList<PACS_Site> PACS_Sites
        {
            get
            {
                return this._PACSSites;
            }
        }

        private IList<CONTACT_TrialSponsor> _CONTACTTrialSponsors = new List<CONTACT_TrialSponsor>();
        public virtual IList<CONTACT_TrialSponsor> CONTACT_TrialSponsors
        {
            get
            {
                return this._CONTACTTrialSponsors;
            }
        }

        private IList<CONTACT_UserTrial> _CONTACTUserTrials = new List<CONTACT_UserTrial>();
        public virtual IList<CONTACT_UserTrial> CONTACT_UserTrials
        {
            get
            {
                return this._CONTACTUserTrials;
            }
        }

        private IList<CERT_Equipment> _CERTEquipments = new List<CERT_Equipment>();
        public virtual IList<CERT_Equipment> CERT_Equipments
        {
            get
            {
                return this._CERTEquipments;
            }
        }

        private IList<GRD_GradingTemplate> _GRDGradingTemplates = new List<GRD_GradingTemplate>();
        public virtual IList<GRD_GradingTemplate> GRD_GradingTemplates
        {
            get
            {
                return this._GRDGradingTemplates;
            }
        }

        private IList<WF_Template> _WFTemplates = new List<WF_Template>();
        public virtual IList<WF_Template> WF_Templates
        {
            get
            {
                return this._WFTemplates;
            }
        }

        private IList<CONTACT_TrialReadingCenter> _CONTACTTrialReadingCenters = new List<CONTACT_TrialReadingCenter>();
        public virtual IList<CONTACT_TrialReadingCenter> CONTACT_TrialReadingCenters
        {
            get
            {
                return this._CONTACTTrialReadingCenters;
            }
        }

        private IList<DOCU_DocumentGroup> _DOCUDocumentGroups = new List<DOCU_DocumentGroup>();
        public virtual IList<DOCU_DocumentGroup> DOCU_DocumentGroups
        {
            get
            {
                return this._DOCUDocumentGroups;
            }
        }

        private IList<QRY_Query> _QRYQueries = new List<QRY_Query>();
        public virtual IList<QRY_Query> QRY_Queries
        {
            get
            {
                return this._QRYQueries;
            }
        }

        //private IList<AUDIT_Record> _AUDITRecords = new List<AUDIT_Record>();
        //public virtual IList<AUDIT_Record> AUDIT_Records
        //{
        //    get
        //    {
        //        return this._AUDITRecords;
        //    }
        //}

        private IList<PACS_SubjectGroup> _PACSSubjectGroups = new List<PACS_SubjectGroup>();
        public virtual IList<PACS_SubjectGroup> PACS_SubjectGroups
        {
            get
            {
                return this._PACSSubjectGroups;
            }
        }

        private IList<PACS_SubjectCohort> _PACSSubjectCohorts = new List<PACS_SubjectCohort>();
        public virtual IList<PACS_SubjectCohort> PACS_SubjectCohorts
        {
            get
            {
                return this._PACSSubjectCohorts;
            }
        }

        private IList<RPT_TrialReport> _RPTTrialReports = new List<RPT_TrialReport>();
        public virtual IList<RPT_TrialReport> RPT_TrialReports
        {
            get
            {
                return this._RPTTrialReports;
            }
        }

        private IList<BGD_Job> _BGDJobs = new List<BGD_Job>();
        public virtual IList<BGD_Job> BGD_Jobs
        {
            get
            {
                return this._BGDJobs;
            }
        }

        private IList<GRD_GradingAnswer> _GRDGradingAnswers = new List<GRD_GradingAnswer>();
        public virtual IList<GRD_GradingAnswer> GRD_GradingAnswers
        {
            get
            {
                return this._GRDGradingAnswers;
            }
        }

        private IList<CRF_Template> _CRFTemplates = new List<CRF_Template>();
        public virtual IList<CRF_Template> CRF_Templates
        {
            get
            {
                return this._CRFTemplates;
            }
        }

        private IList<MEA_Stencil> _MEAStencils = new List<MEA_Stencil>();
        public virtual IList<MEA_Stencil> MEA_Stencils
        {
            get
            {
                return this._MEAStencils;
            }
        }

        private IList<CRF_AnswerValidation> _CRFAnswerValidations = new List<CRF_AnswerValidation>();
        public virtual IList<CRF_AnswerValidation> CRF_AnswerValidations
        {
            get
            {
                return this._CRFAnswerValidations;
            }
        }

        private IList<CERT_ImgProcedureList> _CERTImgProcedureLists = new List<CERT_ImgProcedureList>();
        public virtual IList<CERT_ImgProcedureList> CERT_ImgProcedureLists
        {
            get
            {
                return this._CERTImgProcedureLists;
            }
        }
    }
}
#pragma warning restore 1591
