#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using Excelsior.Domain;

namespace Excelsior.Domain	
{
	public partial class PACS_SubjectGroup
	{
		private long _SubjectGroupID;
		public virtual long SubjectGroupID
		{
			get
			{
				return this._SubjectGroupID;
			}
			set
			{
				this._SubjectGroupID = value;
			}
		}
		
		private long? _TrialID;
		public virtual long? TrialID
		{
			get
			{
				return this._TrialID;
			}
			set
			{
				this._TrialID = value;
			}
		}
		
		private string _GroupName;
		public virtual string GroupName
		{
			get
			{
				return this._GroupName;
			}
			set
			{
				this._GroupName = value;
			}
		}
		
		private string _NumberofSubjects;
		public virtual string NumberofSubjects
		{
			get
			{
				return this._NumberofSubjects;
			}
			set
			{
				this._NumberofSubjects = value;
			}
		}
		
		private string _GroupDescription;
		public virtual string GroupDescription
		{
			get
			{
				return this._GroupDescription;
			}
			set
			{
				this._GroupDescription = value;
			}
		}
		
		private string _DosingInfo;
		public virtual string DosingInfo
		{
			get
			{
				return this._DosingInfo;
			}
			set
			{
				this._DosingInfo = value;
			}
		}
		
		private string _TreatmentEye;
		public virtual string TreatmentEye
		{
			get
			{
				return this._TreatmentEye;
			}
			set
			{
				this._TreatmentEye = value;
			}
		}
		
		private bool _IsActive;
		public virtual bool IsActive
		{
			get
			{
				return this._IsActive;
			}
			set
			{
				this._IsActive = value;
			}
		}
		
		private PACS_Trial _PACSTrial;
		public virtual PACS_Trial PACSTrial
		{
			get
			{
				return this._PACSTrial;
			}
			set
			{
				this._PACSTrial = value;
			}
		}
		
		private IList<PACS_Subject> _PACSSubjects = new List<PACS_Subject>();
		public virtual IList<PACS_Subject> PACS_Subjects
		{
			get
			{
				return this._PACSSubjects;
			}
		}
		
	}
}
#pragma warning restore 1591
