#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using Excelsior.Domain;

namespace Excelsior.Domain	
{
	public partial class PACS_TrialKeyMetric : PACS_Trial
	{
		private double? _TargetUploadTAT;
		public virtual double? TargetUploadTAT
		{
			get
			{
				return this._TargetUploadTAT;
			}
			set
			{
				this._TargetUploadTAT = value;
			}
		}
		
		private double? _TargetTotalTAT;
		public virtual double? TargetTotalTAT
		{
			get
			{
				return this._TargetTotalTAT;
			}
			set
			{
				this._TargetTotalTAT = value;
			}
		}
		
		private double? _TargetTechCertTime;
		public virtual double? TargetTechCertTime
		{
			get
			{
				return this._TargetTechCertTime;
			}
			set
			{
				this._TargetTechCertTime = value;
			}
		}
		
		private double? _TargetSubjectsEnrolled;
		public virtual double? TargetSubjectsEnrolled
		{
			get
			{
				return this._TargetSubjectsEnrolled;
			}
			set
			{
				this._TargetSubjectsEnrolled = value;
			}
		}
		
		private double? _TargetSeriesCollected;
		public virtual double? TargetSeriesCollected
		{
			get
			{
				return this._TargetSeriesCollected;
			}
			set
			{
				this._TargetSeriesCollected = value;
			}
		}
		
		private double? _TargetQueryTAT;
		public virtual double? TargetQueryTAT
		{
			get
			{
				return this._TargetQueryTAT;
			}
			set
			{
				this._TargetQueryTAT = value;
			}
		}
		
		private double? _TargetQueryRatio;
		public virtual double? TargetQueryRatio
		{
			get
			{
				return this._TargetQueryRatio;
			}
			set
			{
				this._TargetQueryRatio = value;
			}
		}
		
		private double? _TargetPercentSuboptimalData;
		public virtual double? TargetPercentSuboptimalData
		{
			get
			{
				return this._TargetPercentSuboptimalData;
			}
			set
			{
				this._TargetPercentSuboptimalData = value;
			}
		}
		
		private double? _TargetGradingTAT;
		public virtual double? TargetGradingTAT
		{
			get
			{
				return this._TargetGradingTAT;
			}
			set
			{
				this._TargetGradingTAT = value;
			}
		}
		
		private double? _TargetEqmtCertTime;
		public virtual double? TargetEqmtCertTime
		{
			get
			{
				return this._TargetEqmtCertTime;
			}
			set
			{
				this._TargetEqmtCertTime = value;
			}
		}
		
		private double? _TargetEligibilityTotalTAT;
		public virtual double? TargetEligibilityTotalTAT
		{
			get
			{
				return this._TargetEligibilityTotalTAT;
			}
			set
			{
				this._TargetEligibilityTotalTAT = value;
			}
		}
		
		private double? _TargetEligibilityGradingTAT;
		public virtual double? TargetEligibilityGradingTAT
		{
			get
			{
				return this._TargetEligibilityGradingTAT;
			}
			set
			{
				this._TargetEligibilityGradingTAT = value;
			}
		}
		
		private double? _TargetEligibilityCheckinTAT;
		public virtual double? TargetEligibilityCheckinTAT
		{
			get
			{
				return this._TargetEligibilityCheckinTAT;
			}
			set
			{
				this._TargetEligibilityCheckinTAT = value;
			}
		}
		
		private double? _TargetCheckinTAT;
		public virtual double? TargetCheckinTAT
		{
			get
			{
				return this._TargetCheckinTAT;
			}
			set
			{
				this._TargetCheckinTAT = value;
			}
		}
		
	}
}
#pragma warning restore 1591
