#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using Excelsior.Domain;

namespace Excelsior.Domain	
{
	public partial class PACS_SeriesComment
	{
		private long _SCommentID;
		public virtual long SCommentID
		{
			get
			{
				return this._SCommentID;
			}
			set
			{
				this._SCommentID = value;
			}
		}
		
		private long? _SeriesID;
		public virtual long? SeriesID
		{
			get
			{
				return this._SeriesID;
			}
			set
			{
				this._SeriesID = value;
			}
		}
		
		private string _CommentText;
		public virtual string CommentText
		{
			get
			{
				return this._CommentText;
			}
			set
			{
				this._CommentText = value;
			}
		}
		
		private DateTime? _CreatedDate;
		public virtual DateTime? CreatedDate
		{
			get
			{
				return this._CreatedDate;
			}
			set
			{
				this._CreatedDate = value;
			}
		}
		
		private long? _UserID;
		public virtual long? UserID
		{
			get
			{
				return this._UserID;
			}
			set
			{
				this._UserID = value;
			}
		}
		
		private PACS_Series _PACSSeries;
		public virtual PACS_Series PACSSeries
		{
			get
			{
				return this._PACSSeries;
			}
			set
			{
				this._PACSSeries = value;
			}
		}
		
		private CONTACT_User _CONTACTUser;
		public virtual CONTACT_User CONTACTUser
		{
			get
			{
				return this._CONTACTUser;
			}
			set
			{
				this._CONTACTUser = value;
			}
		}
		
	}
}
#pragma warning restore 1591
