#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using Excelsior.Domain;

namespace Excelsior.Domain	
{
	public partial class PACS_DicomOPT : PACS_RawDatum
	{
		private double? _PixelSpacingY;
		public virtual double? PixelSpacingY
		{
			get
			{
				return this._PixelSpacingY;
			}
			set
			{
				this._PixelSpacingY = value;
			}
		}
		
		private double? _PixelSpacingX;
		public virtual double? PixelSpacingX
		{
			get
			{
				return this._PixelSpacingX;
			}
			set
			{
				this._PixelSpacingX = value;
			}
		}
		
		private double? _FrameSpacing;
		public virtual double? FrameSpacing
		{
			get
			{
				return this._FrameSpacing;
			}
			set
			{
				this._FrameSpacing = value;
			}
		}
		
		private int? _ImageWidth;
		public virtual int? ImageWidth
		{
			get
			{
				return this._ImageWidth;
			}
			set
			{
				this._ImageWidth = value;
			}
		}
		
		private int? _ImageHeight;
		public virtual int? ImageHeight
		{
			get
			{
				return this._ImageHeight;
			}
			set
			{
				this._ImageHeight = value;
			}
		}
		
		private long? _RefRawDataID;
		public virtual long? RefRawDataID
		{
			get
			{
				return this._RefRawDataID;
			}
			set
			{
				this._RefRawDataID = value;
			}
		}
		
		private string _RefImageCoveredArea;
		public virtual string RefImageCoveredArea
		{
			get
			{
				return this._RefImageCoveredArea;
			}
			set
			{
				this._RefImageCoveredArea = value;
			}
		}
		
		private string _RefDCMInstanceUID;
		public virtual string RefDCMInstanceUID
		{
			get
			{
				return this._RefDCMInstanceUID;
			}
			set
			{
				this._RefDCMInstanceUID = value;
			}
		}
		
		private string _ScanType;
		public virtual string ScanType
		{
			get
			{
				return this._ScanType;
			}
			set
			{
				this._ScanType = value;
			}
		}
		
		private PACS_RawDatum _PACSRawDatum;
		public virtual PACS_RawDatum ScoutImage
		{
			get
			{
				return this._PACSRawDatum;
			}
			set
			{
				this._PACSRawDatum = value;
			}
		}
		
	}
}
#pragma warning restore 1591
