#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using Excelsior.Domain;

namespace Excelsior.Domain	
{
	public partial class PACS_Site
	{
		private long? _TrialID;
		public virtual long? TrialID
		{
			get
			{
				return this._TrialID;
			}
			set
			{
				this._TrialID = value;
			}
		}
		
		private long _SiteID;
		public virtual long SiteID
		{
			get
			{
				return this._SiteID;
			}
			set
			{
				this._SiteID = value;
			}
		}
		
		private string _RandomizedSiteID;
		public virtual string RandomizedSiteID
		{
			get
			{
				return this._RandomizedSiteID;
			}
			set
			{
				this._RandomizedSiteID = value;
			}
		}
		
		private long? _AffiliationID;
		public virtual long? AffiliationID
		{
			get
			{
				return this._AffiliationID;
			}
			set
			{
				this._AffiliationID = value;
			}
		}
		
		private bool _IsIRB;
		public virtual bool IsIRB
		{
			get
			{
				return this._IsIRB;
			}
			set
			{
				this._IsIRB = value;
			}
		}
		
		private bool _IsTestingSite;
		public virtual bool IsTestingSite
		{
			get
			{
				return this._IsTestingSite;
			}
			set
			{
				this._IsTestingSite = value;
			}
		}
		
		private string _PrincipalInvestigator;
		public virtual string PrincipalInvestigator
		{
			get
			{
				return this._PrincipalInvestigator;
			}
			set
			{
				this._PrincipalInvestigator = value;
			}
		}
		
		private bool _IsActive;
		public virtual bool IsActive
		{
			get
			{
				return this._IsActive;
			}
			set
			{
				this._IsActive = value;
			}
		}
		
		private PACS_Trial _PACSTrial;
		public virtual PACS_Trial PACSTrial
		{
			get
			{
				return this._PACSTrial;
			}
			set
			{
				this._PACSTrial = value;
			}
		}
		
		private CONTACT_Affiliation _CONTACTAffiliation;
		public virtual CONTACT_Affiliation CONTACTAffiliation
		{
			get
			{
				return this._CONTACTAffiliation;
			}
			set
			{
				this._CONTACTAffiliation = value;
			}
		}
		
		private IList<PACS_Subject> _PACSSubjects = new List<PACS_Subject>();
		public virtual IList<PACS_Subject> PACS_Subjects
		{
			get
			{
				return this._PACSSubjects;
			}
		}
		
	}
}
#pragma warning restore 1591
