#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using Excelsior.Domain;

namespace Excelsior.Domain	
{
	public partial class PACS_Subject
	{
		private long? _SiteID;
		public virtual long? SiteID
		{
			get
			{
				return this._SiteID;
			}
			set
			{
				this._SiteID = value;
			}
		}
		
		private string _RandomizedSubjectID;
		public virtual string RandomizedSubjectID
		{
			get
			{
				return this._RandomizedSubjectID;
			}
			set
			{
				this._RandomizedSubjectID = value;
			}
		}
		
		private string _AlternativeRandomizedSubjectID;
		public virtual string AlternativeRandomizedSubjectID
		{
			get
			{
				return this._AlternativeRandomizedSubjectID;
			}
			set
			{
				this._AlternativeRandomizedSubjectID = value;
			}
		}
		
		private string _NameCode;
		public virtual string NameCode
		{
			get
			{
				return this._NameCode;
			}
			set
			{
				this._NameCode = value;
			}
		}
		
		private int? _BirthYear;
		public virtual int? BirthYear
		{
			get
			{
				return this._BirthYear;
			}
			set
			{
				this._BirthYear = value;
			}
		}
		
		private bool _IsActive;
		public virtual bool IsActive
		{
			get
			{
				return this._IsActive;
			}
			set
			{
				this._IsActive = value;
			}
		}
		
		private bool _IsValidated;
		public virtual bool IsValidated
		{
			get
			{
				return this._IsValidated;
			}
			set
			{
				this._IsValidated = value;
			}
		}
		
		private long _SubjectID;
		public virtual long SubjectID
		{
			get
			{
				return this._SubjectID;
			}
			set
			{
				this._SubjectID = value;
			}
		}
		
		private string _Laterality;
		public virtual string Laterality
		{
			get
			{
				return this._Laterality;
			}
			set
			{
				this._Laterality = value;
			}
		}
		
		private bool _IsSubjectRejected;
		public virtual bool IsSubjectRejected
		{
			get
			{
				return this._IsSubjectRejected;
			}
			set
			{
				this._IsSubjectRejected = value;
			}
		}
		
		private bool _IsTestingSubject;
		public virtual bool IsTestingSubject
		{
			get
			{
				return this._IsTestingSubject;
			}
			set
			{
				this._IsTestingSubject = value;
			}
		}
		
		private long? _SubjectGroupID;
		public virtual long? SubjectGroupID
		{
			get
			{
				return this._SubjectGroupID;
			}
			set
			{
				this._SubjectGroupID = value;
			}
		}
		
		private DateTime? _SubjectEnrollmentDate;
		public virtual DateTime? SubjectEnrollmentDate
		{
			get
			{
				return this._SubjectEnrollmentDate;
			}
			set
			{
				this._SubjectEnrollmentDate = value;
			}
		}
		
		private long? _SubjectCohortID;
		public virtual long? SubjectCohortID
		{
			get
			{
				return this._SubjectCohortID;
			}
			set
			{
				this._SubjectCohortID = value;
			}
		}
		
		private string _Gender;
		public virtual string Gender
		{
			get
			{
				return this._Gender;
			}
			set
			{
				this._Gender = value;
			}
		}
		
		private bool _IsDismissed;
		public virtual bool IsDismissed
		{
			get
			{
				return this._IsDismissed;
			}
			set
			{
				this._IsDismissed = value;
			}
		}
		
		private PACS_Site _PACSSite;
		public virtual PACS_Site PACSSite
		{
			get
			{
				return this._PACSSite;
			}
			set
			{
				this._PACSSite = value;
			}
		}
		
		private PACS_SubjectCohort _PACSSubjectCohort;
		public virtual PACS_SubjectCohort PACSSubjectCohort
		{
			get
			{
				return this._PACSSubjectCohort;
			}
			set
			{
				this._PACSSubjectCohort = value;
			}
		}
		
		private PACS_SubjectGroup _PACSSubjectGroup;
		public virtual PACS_SubjectGroup PACSSubjectGroup
		{
			get
			{
				return this._PACSSubjectGroup;
			}
			set
			{
				this._PACSSubjectGroup = value;
			}
		}
		
		private IList<PACS_TimePoint> _PACSTimePoints = new List<PACS_TimePoint>();
		public virtual IList<PACS_TimePoint> PACS_TimePoints
		{
			get
			{
				return this._PACSTimePoints;
			}
		}
		
		//private IList<AUDIT_Record> _AUDITRecords = new List<AUDIT_Record>();
		//public virtual IList<AUDIT_Record> AUDIT_Records
		//{
		//	get
		//	{
		//		return this._AUDITRecords;
		//	}
		//}

        private IList<CRF_Datum> _CRFData = new List<CRF_Datum>();
        public virtual IList<CRF_Datum> CRF_Data
        {
            get
            {
                return this._CRFData;
            }
        }
    }
}
#pragma warning restore 1591
