#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using Excelsior.Domain;

namespace Excelsior.Domain	
{
	public partial class PACS_DicomOP : PACS_RawDatum
	{
		private double? _PixelSpacingY;
		public virtual double? PixelSpacingY
		{
			get
			{
				return this._PixelSpacingY;
			}
			set
			{
				this._PixelSpacingY = value;
			}
		}
		
		private double? _PixelSpacingX;
		public virtual double? PixelSpacingX
		{
			get
			{
				return this._PixelSpacingX;
			}
			set
			{
				this._PixelSpacingX = value;
			}
		}
		
		private string _BolusTime;
		public virtual string BolusTime
		{
			get
			{
				return this._BolusTime;
			}
			set
			{
				this._BolusTime = value;
			}
		}
		
		private string _AcquisitionTime;
		public virtual string AcquisitionTime
		{
			get
			{
				return this._AcquisitionTime;
			}
			set
			{
				this._AcquisitionTime = value;
			}
		}
		
		private int? _ImageWidth;
		public virtual int? ImageWidth
		{
			get
			{
				return this._ImageWidth;
			}
			set
			{
				this._ImageWidth = value;
			}
		}
		
		private int? _ImageHeight;
		public virtual int? ImageHeight
		{
			get
			{
				return this._ImageHeight;
			}
			set
			{
				this._ImageHeight = value;
			}
		}
		
	}
}
#pragma warning restore 1591
