#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using Excelsior.Domain;

namespace Excelsior.Domain	
{
	public partial class PACS_TimePointsList
	{
		private long? _TrialID;
		public virtual long? TrialID
		{
			get
			{
				return this._TrialID;
			}
			set
			{
				this._TrialID = value;
			}
		}
		
		private int? _TimePointsSeq;
		public virtual int? TimePointsSeq
		{
			get
			{
				return this._TimePointsSeq;
			}
			set
			{
				this._TimePointsSeq = value;
			}
		}
		
		private long _TimePointsListID;
		public virtual long TimePointsListID
		{
			get
			{
				return this._TimePointsListID;
			}
			set
			{
				this._TimePointsListID = value;
			}
		}
		
		private string _TimePointsDescription;
		public virtual string TimePointsDescription
		{
			get
			{
				return this._TimePointsDescription;
			}
			set
			{
				this._TimePointsDescription = value;
			}
		}
		
		private bool _IsInitialTimePoint;
		public virtual bool IsInitialTimePoint
		{
			get
			{
				return this._IsInitialTimePoint;
			}
			set
			{
				this._IsInitialTimePoint = value;
			}
		}
		
		private bool _IsTerminalTimePoint;
		public virtual bool IsTerminalTimePoint
		{
			get
			{
				return this._IsTerminalTimePoint;
			}
			set
			{
				this._IsTerminalTimePoint = value;
			}
		}
		
		private bool _IsEligibilityTimePoint;
		public virtual bool IsEligibilityTimePoint
		{
			get
			{
				return this._IsEligibilityTimePoint;
			}
			set
			{
				this._IsEligibilityTimePoint = value;
			}
		}
		
		private int? _ExpectedVisitStartDay;
		public virtual int? ExpectedVisitStartDay
		{
			get
			{
				return this._ExpectedVisitStartDay;
			}
			set
			{
				this._ExpectedVisitStartDay = value;
			}
		}
		
		private int? _ExpectedVisitEndDay;
		public virtual int? ExpectedVisitEndDay
		{
			get
			{
				return this._ExpectedVisitEndDay;
			}
			set
			{
				this._ExpectedVisitEndDay = value;
			}
		}
		
		private PACS_Trial _PACSTrial;
		public virtual PACS_Trial PACSTrial
		{
			get
			{
				return this._PACSTrial;
			}
			set
			{
				this._PACSTrial = value;
			}
		}
		
		private IList<PACS_TPProcList> _PACSTPProcLists = new List<PACS_TPProcList>();
		public virtual IList<PACS_TPProcList> PACS_TPProcLists
		{
			get
			{
				return this._PACSTPProcLists;
			}
		}
		
		private IList<PACS_TimePoint> _PACSTimePoints = new List<PACS_TimePoint>();
		public virtual IList<PACS_TimePoint> PACS_TimePoints
		{
			get
			{
				return this._PACSTimePoints;
			}
		}
		
	}
}
#pragma warning restore 1591
