#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using Excelsior.Domain;

namespace Excelsior.Domain	
{
	public partial class PACS_DataType
	{
		private long _DataTypeID;
		public virtual long DataTypeID
		{
			get
			{
				return this._DataTypeID;
			}
			set
			{
				this._DataTypeID = value;
			}
		}
		
		private string _DataType;
		public virtual string DataType
		{
			get
			{
				return this._DataType;
			}
			set
			{
				this._DataType = value;
			}
		}
		
		private IList<CERT_ImgProcedureList> _CERTImgProcedureLists = new List<CERT_ImgProcedureList>();
		public virtual IList<CERT_ImgProcedureList> CERT_ImgProcedureLists
		{
			get
			{
				return this._CERTImgProcedureLists;
			}
		}
		
		private IList<PACS_RawDatum> _PACSRawData = new List<PACS_RawDatum>();
		public virtual IList<PACS_RawDatum> PACS_RawData
		{
			get
			{
				return this._PACSRawData;
			}
		}
		
		private IList<MEA_MeasDataType> _MEAMeasDataTypes = new List<MEA_MeasDataType>();
		public virtual IList<MEA_MeasDataType> MEA_MeasDataTypes
		{
			get
			{
				return this._MEAMeasDataTypes;
			}
		}
		
	}
}
#pragma warning restore 1591
