#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using Excelsior.Domain;

namespace Excelsior.Domain	
{
	public partial class PACS_TimePoint
	{
		private long? _TimePointsListID;
		public virtual long? TimePointsListID
		{
			get
			{
				return this._TimePointsListID;
			}
			set
			{
				this._TimePointsListID = value;
			}
		}
		
		private long _TimePointsID;
		public virtual long TimePointsID
		{
			get
			{
				return this._TimePointsID;
			}
			set
			{
				this._TimePointsID = value;
			}
		}
		
		private string _TimePointsDCMInstanceUID;
		public virtual string TimePointsDCMInstanceUID
		{
			get
			{
				return this._TimePointsDCMInstanceUID;
			}
			set
			{
				this._TimePointsDCMInstanceUID = value;
			}
		}
		
		private long? _SubjectID;
		public virtual long? SubjectID
		{
			get
			{
				return this._SubjectID;
			}
			set
			{
				this._SubjectID = value;
			}
		}
		
		private PACS_TimePointsList _PACSTimePointsList;
		public virtual PACS_TimePointsList PACSTimePointsList
		{
			get
			{
				return this._PACSTimePointsList;
			}
			set
			{
				this._PACSTimePointsList = value;
			}
		}
		
		private PACS_Subject _PACSSubject;
		public virtual PACS_Subject PACSSubject
		{
			get
			{
				return this._PACSSubject;
			}
			set
			{
				this._PACSSubject = value;
			}
		}
		
		private IList<PACS_Series> _PACSSeries = new List<PACS_Series>();
		public virtual IList<PACS_Series> PACS_Series
		{
			get
			{
				return this._PACSSeries;
			}
		}
		
		private IList<PACS_SeriesGroup> _PACSSeriesGroups = new List<PACS_SeriesGroup>();
		public virtual IList<PACS_SeriesGroup> PACS_SeriesGroups
		{
			get
			{
				return this._PACSSeriesGroups;
			}
		}
		
	}
}
#pragma warning restore 1591
