#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using Excelsior.Domain;

namespace Excelsior.Domain	
{
	public partial class PACS_SeriesAttachment
	{
		private long _SeriesAttachmentID;
		public virtual long SeriesAttachmentID
        {
			get
			{
				return this._SeriesAttachmentID;
			}
			set
			{
				this._SeriesAttachmentID = value;
			}
		}
		
		private DateTime? _DateCreated;
		public virtual DateTime? DateCreated
        {
			get
			{
				return this._DateCreated;
			}
			set
			{
				this._DateCreated = value;
			}
		}
		
		private long? _UserID;
		public virtual long? UserID
        {
			get
			{
				return this._UserID;
			}
			set
			{
				this._UserID = value;
			}
		}
		
		private long? _SeriesID;
		public virtual long? SeriesID
		{
			get
			{
				return this._SeriesID;
			}
			set
			{
				this._SeriesID = value;
			}
		}

        private long? _GReportID;
        public virtual long? GReportID
        {
            get
            {
                return this._GReportID;
            }
            set
            {
                this._GReportID = value;
            }
        }

        private string _FileLocation;
		public virtual string FileLocation
		{
			get
			{
				return this._FileLocation;
			}
			set
			{
				this._FileLocation = value;
			}
		}
		
		private bool _IsActive;
		public virtual bool IsActive
		{
			get
			{
				return this._IsActive;
			}
			set
			{
				this._IsActive = value;
			}
		}
		
		private string _Laterality;
		public virtual string Laterality
		{
			get
			{
				return this._Laterality;
			}
			set
			{
				this._Laterality = value;
			}
		}

        private long? _StatusID;
        public virtual long? StatusID
        {
            get
            {
                return this._StatusID;
            }
            set
            {
                this._StatusID = value;
            }
        }

        private PACS_RawDataStatus _UploadStatus;
        public virtual PACS_RawDataStatus UploadStatus
        {
            get
            {
                return this._UploadStatus;
            }
            set
            {
                this._UploadStatus = value;
            }
        }

        private PACS_Series _PACSSeries;
		public virtual PACS_Series PACSSeries
		{
			get
			{
				return this._PACSSeries;
			}
			set
			{
				this._PACSSeries = value;
			}
		}

        private GRD_Report _GRDReport;
        public virtual GRD_Report GRDReport
        {
            get
            {
                return this._GRDReport;
            }
            set
            {
                this._GRDReport = value;
            }
        }

        private CONTACT_User _CONTACTUser;
		public virtual CONTACT_User CONTACTUser
		{
			get
			{
				return this._CONTACTUser;
			}
			set
			{
				this._CONTACTUser = value;
			}
		}		
	}
}
#pragma warning restore 1591
