#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using Excelsior.Domain;

namespace Excelsior.Domain	
{
	public partial class QRY_Query
	{
		private long? _SeriesID;
		public virtual long? SeriesID
		{
			get
			{
				return this._SeriesID;
			}
			set
			{
				this._SeriesID = value;
			}
		}
		
		private long? _RecipientID;
		public virtual long? RecipientID
		{
			get
			{
				return this._RecipientID;
			}
			set
			{
				this._RecipientID = value;
			}
		}
		
		private long _QueryID;
		public virtual long QueryID
		{
			get
			{
				return this._QueryID;
			}
			set
			{
				this._QueryID = value;
			}
		}
		
		private bool _IsResolved;
		public virtual bool IsResolved
		{
			get
			{
				return this._IsResolved;
			}
			set
			{
				this._IsResolved = value;
			}
		}

        private long? _StatusID;
        public virtual long? StatusID
        {
            get
            {
                return this._StatusID;
            }
            set
            {
                this._StatusID = value;
            }
        }

        private bool _DeactivateSeries;
		public virtual bool DeactivateSeries
		{
			get
			{
				return this._DeactivateSeries;
			}
			set
			{
				this._DeactivateSeries = value;
			}
		}
		
		private bool _ActionRequired;
		public virtual bool ActionRequired
		{
			get
			{
				return this._ActionRequired;
			}
			set
			{
				this._ActionRequired = value;
			}
		}
		
		private string _Subject;
		public virtual string Subject
		{
			get
			{
				return this._Subject;
			}
			set
			{
				this._Subject = value;
			}
		}
		
		private long? _SenderID;
		public virtual long? SenderID
		{
			get
			{
				return this._SenderID;
			}
			set
			{
				this._SenderID = value;
			}
		}
		
		private DateTime? _DateResolved;
		public virtual DateTime? DateResolved
		{
			get
			{
				return this._DateResolved;
			}
			set
			{
				this._DateResolved = value;
			}
		}
		
		private DateTime? _InitiateDate;
		public virtual DateTime? InitiateDate
		{
			get
			{
				return this._InitiateDate;
			}
			set
			{
				this._InitiateDate = value;
			}
		}
		
		private long? _TrialID;
		public virtual long? TrialID
		{
			get
			{
				return this._TrialID;
			}
			set
			{
				this._TrialID = value;
			}
		}
		
		private long? _CertUserID;
		public virtual long? CertUserID
		{
			get
			{
				return this._CertUserID;
			}
			set
			{
				this._CertUserID = value;
			}
		}
		
		private long? _CertEquipmentID;
		public virtual long? CertEquipmentID
		{
			get
			{
				return this._CertEquipmentID;
			}
			set
			{
				this._CertEquipmentID = value;
			}
		}

        private bool _IsActive;
        public virtual bool IsActive
        {
            get
            {
                return this._IsActive;
            }
            set
            {
                this._IsActive = value;
            }
        }

        private QRY_Status _QRYStatus;
        public virtual QRY_Status QRYStatus
        {
            get
            {
                return this._QRYStatus;
            }
            set
            {
                this._QRYStatus = value;
            }
        }

        private PACS_Series _PACSSeries;
		public virtual PACS_Series PACSSeries
		{
			get
			{
				return this._PACSSeries;
			}
			set
			{
				this._PACSSeries = value;
			}
		}
		
		private CONTACT_User _Recipient;
		public virtual CONTACT_User Recipient
		{
			get
			{
				return this._Recipient;
			}
			set
			{
				this._Recipient = value;
			}
		}
		
		private CONTACT_User _Sender;
		public virtual CONTACT_User Sender
		{
			get
			{
				return this._Sender;
			}
			set
			{
				this._Sender = value;
			}
		}
		
		private PACS_Trial _PACSTrial;
		public virtual PACS_Trial PACSTrial
		{
			get
			{
				return this._PACSTrial;
			}
			set
			{
				this._PACSTrial = value;
			}
		}
		
		private CERT_User _CERTUser;
		public virtual CERT_User CERTUser
		{
			get
			{
				return this._CERTUser;
			}
			set
			{
				this._CERTUser = value;
			}
		}
		
		private CERT_Equipment _CERTEquipment;
		public virtual CERT_Equipment CERTEquipment
		{
			get
			{
				return this._CERTEquipment;
			}
			set
			{
				this._CERTEquipment = value;
			}
		}
		
		private IList<QRY_Message> _QRYMessages = new List<QRY_Message>();
		public virtual IList<QRY_Message> QRY_Messages
		{
			get
			{
				return this._QRYMessages;
			}
		}
		
		private IList<CERT_UploadInfo> _CERTUploadInfos = new List<CERT_UploadInfo>();
		public virtual IList<CERT_UploadInfo> CERT_UploadInfos
		{
			get
			{
				return this._CERTUploadInfos;
			}
		}
		
	}
}
#pragma warning restore 1591
