#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using Excelsior.Domain;

namespace Excelsior.Domain	
{
	public partial class QRY_Message
	{
		private int? _SeqCount;
		public virtual int? SeqCount
		{
			get
			{
				return this._SeqCount;
			}
			set
			{
				this._SeqCount = value;
			}
		}
		
		private long? _QueryID;
		public virtual long? QueryID
		{
			get
			{
				return this._QueryID;
			}
			set
			{
				this._QueryID = value;
			}
		}

        private long? _UserID;
        public virtual long? UserID
        {
            get
            {
                return this._UserID;
            }
            set
            {
                this._UserID = value;
            }
        }

        private long _MessageID;
		public virtual long MessageID
		{
			get
			{
				return this._MessageID;
			}
			set
			{
				this._MessageID = value;
			}
		}
		
		private string _MessageBody;
		public virtual string MessageBody
		{
			get
			{
				return this._MessageBody;
			}
			set
			{
				this._MessageBody = value;
			}
		}
		
		private DateTime? _DateCreated;
		public virtual DateTime? DateCreated
		{
			get
			{
				return this._DateCreated;
			}
			set
			{
				this._DateCreated = value;
			}
		}
		
		private bool _IsRequest;
		public virtual bool IsRequest
		{
			get
			{
				return this._IsRequest;
			}
			set
			{
				this._IsRequest = value;
			}
		}
		
		private bool _HasResponded;
		public virtual bool HasResponded
		{
			get
			{
				return this._HasResponded;
			}
			set
			{
				this._HasResponded = value;
			}
		}

        private bool _IsActive;
        public virtual bool IsActive
        {
            get
            {
                return this._IsActive;
            }
            set
            {
                this._IsActive = value;
            }
        }

        private QRY_Query _QRYQuery;
		public virtual QRY_Query QRYQuery
		{
			get
			{
				return this._QRYQuery;
			}
			set
			{
				this._QRYQuery = value;
			}
		}

        private CONTACT_User _CONTACTUser;
        public virtual CONTACT_User CONTACTUser
        {
            get
            {
                return this._CONTACTUser;
            }
            set
            {
                this._CONTACTUser = value;
            }
        }
    }
}
#pragma warning restore 1591
