#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using Excelsior.Domain;

namespace Excelsior.Domain	
{
	public partial class RPT_Report
	{
		private long _ReportID;
		public virtual long ReportID
		{
			get
			{
				return this._ReportID;
			}
			set
			{
				this._ReportID = value;
			}
		}
		
		private string _ReportName;
		public virtual string ReportName
		{
			get
			{
				return this._ReportName;
			}
			set
			{
				this._ReportName = value;
			}
		}
		
		private string _ReportClass;
		public virtual string ReportClass
		{
			get
			{
				return this._ReportClass;
			}
			set
			{
				this._ReportClass = value;
			}
		}

        private string _ReportAPIClass;
        public virtual string ReportAPIClass
        {
            get
            {
                return this._ReportAPIClass;
            }
            set
            {
                this._ReportAPIClass = value;
            }
        }

        private bool _IsActive;
        public virtual bool IsActive
        {
            get
            {
                return this._IsActive;
            }
            set
            {
                this._IsActive = value;
            }
        }

        private long? _ReportCategoryID;
		public virtual long? ReportCategoryID
		{
			get
			{
				return this._ReportCategoryID;
			}
			set
			{
				this._ReportCategoryID = value;
			}
		}
		
		private RPT_ReportCategory _RPTReportCategory;
		public virtual RPT_ReportCategory RPTReportCategory
		{
			get
			{
				return this._RPTReportCategory;
			}
			set
			{
				this._RPTReportCategory = value;
			}
		}
		
		private IList<RPT_TrialReport> _RPTTrialReports = new List<RPT_TrialReport>();
		public virtual IList<RPT_TrialReport> RPT_TrialReports
		{
			get
			{
				return this._RPTTrialReports;
			}
		}
		
	}
}
#pragma warning restore 1591
