#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using Excelsior.Domain;

namespace Excelsior.Domain	
{
	public partial class RPT_TrialReport
	{
		private long _TrialReportID;
		public virtual long TrialReportID
		{
			get
			{
				return this._TrialReportID;
			}
			set
			{
				this._TrialReportID = value;
			}
		}
		
		private long? _TrialID;
		public virtual long? TrialID
		{
			get
			{
				return this._TrialID;
			}
			set
			{
				this._TrialID = value;
			}
		}
		
		private long? _ReportID;
		public virtual long? ReportID
		{
			get
			{
				return this._ReportID;
			}
			set
			{
				this._ReportID = value;
			}
		}
		
		private string _ReportAlias;
		public virtual string ReportAlias
		{
			get
			{
				return this._ReportAlias;
			}
			set
			{
				this._ReportAlias = value;
			}
		}
		
		private RPT_Report _RPTReport;
		public virtual RPT_Report RPTReport
		{
			get
			{
				return this._RPTReport;
			}
			set
			{
				this._RPTReport = value;
			}
		}
		
		private PACS_Trial _PACSTrial;
		public virtual PACS_Trial PACSTrial
		{
			get
			{
				return this._PACSTrial;
			}
			set
			{
				this._PACSTrial = value;
			}
		}
		
		private IList<RPT_TrialReportRole> _RPTTrialReportRoles = new List<RPT_TrialReportRole>();
		public virtual IList<RPT_TrialReportRole> RPT_TrialReportRoles
		{
			get
			{
				return this._RPTTrialReportRoles;
			}
		}
		
	}
}
#pragma warning restore 1591
