#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using Excelsior.Domain;

namespace Excelsior.Domain	
{
	public partial class RPT_ReportCategory
	{
		private long _ReportCategoryID;
		public virtual long ReportCategoryID
		{
			get
			{
				return this._ReportCategoryID;
			}
			set
			{
				this._ReportCategoryID = value;
			}
		}
		
		private string _ReportCategoryName;
		public virtual string ReportCategoryName
		{
			get
			{
				return this._ReportCategoryName;
			}
			set
			{
				this._ReportCategoryName = value;
			}
		}
		
		private IList<RPT_Report> _RPTReports = new List<RPT_Report>();
		public virtual IList<RPT_Report> RPT_Reports
		{
			get
			{
				return this._RPTReports;
			}
		}
		
	}
}
#pragma warning restore 1591
