#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using Excelsior.Domain;

namespace Excelsior.Domain	
{
	public partial class RPT_TrialReportRole
	{
		private long _TrialReportID;
		public virtual long TrialReportID
		{
			get
			{
				return this._TrialReportID;
			}
			set
			{
				this._TrialReportID = value;
			}
		}
		
		private Guid _RoleId;
		public virtual Guid RoleId
		{
			get
			{
				return this._RoleId;
			}
			set
			{
				this._RoleId = value;
			}
		}
		
		private RPT_TrialReport _RPTTrialReport;
		public virtual RPT_TrialReport RPTTrialReport
		{
			get
			{
				return this._RPTTrialReport;
			}
			set
			{
				this._RPTTrialReport = value;
			}
		}
		
		private Aspnet_Role _AspnetRole;
		public virtual Aspnet_Role AspnetRole
		{
			get
			{
				return this._AspnetRole;
			}
			set
			{
				this._AspnetRole = value;
			}
		}
		
	}
}
#pragma warning restore 1591
