#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using Excelsior.Domain;

namespace Excelsior.Domain	
{
	public partial class UPLD_UploadInfo
	{
		private long _UploadInfoID;
		public virtual long UploadInfoID
		{
			get
			{
				return this._UploadInfoID;
			}
			set
			{
				this._UploadInfoID = value;
			}
		}
		
		private DateTime? _UploadDate;
		public virtual DateTime? UploadDate
		{
			get
			{
				return this._UploadDate;
			}
			set
			{
				this._UploadDate = value;
			}
		}
		
		private long? _UploaderID;
		public virtual long? UploaderID
		{
			get
			{
				return this._UploaderID;
			}
			set
			{
				this._UploaderID = value;
			}
		}
		
		private long? _SeriesID;
		public virtual long? SeriesID
		{
			get
			{
				return this._SeriesID;
			}
			set
			{
				this._SeriesID = value;
			}
		}
		
		private DateTime? _PhotoDate;
		public virtual DateTime? PhotoDate
		{
			get
			{
				return this._PhotoDate;
			}
			set
			{
				this._PhotoDate = value;
			}
		}
		
		private string _DataFileLocation;
		public virtual string DataFileLocation
		{
			get
			{
				return this._DataFileLocation;
			}
			set
			{
				this._DataFileLocation = value;
			}
		}
		
		private string _UploadNote;
		public virtual string UploadNote
		{
			get
			{
				return this._UploadNote;
			}
			set
			{
				this._UploadNote = value;
			}
		}
		
		private bool _IsActive;
		public virtual bool IsActive
		{
			get
			{
				return this._IsActive;
			}
			set
			{
				this._IsActive = value;
			}
		}
		
		private string _Laterality;
		public virtual string Laterality
		{
			get
			{
				return this._Laterality;
			}
			set
			{
				this._Laterality = value;
			}
		}

        private long? _StatusID;
        public virtual long? StatusID
        {
            get
            {
                return this._StatusID;
            }
            set
            {
                this._StatusID = value;
            }
        }

        private string _LastError;
        public virtual string LastError
        {
            get
            {
                return this._LastError;
            }
            set
            {
                this._LastError = value;
            }
        }

        private bool _HasError;
        public virtual bool HasError
        {
            get
            {
                return this._HasError;
            }
            set
            {
                this._HasError = value;
            }
        }

        private PACS_RawDataStatus _PACSRawDataStatus;
        public virtual PACS_RawDataStatus PACSRawDataStatus
        {
            get
            {
                return this._PACSRawDataStatus;
            }
            set
            {
                this._PACSRawDataStatus = value;
            }
        }

        private PACS_Series _PACSSeries;
		public virtual PACS_Series PACSSeries
		{
			get
			{
				return this._PACSSeries;
			}
			set
			{
				this._PACSSeries = value;
			}
		}
		
		private CONTACT_User _CONTACTUser;
		public virtual CONTACT_User CONTACTUser
		{
			get
			{
				return this._CONTACTUser;
			}
			set
			{
				this._CONTACTUser = value;
			}
		}
		
	}
}
#pragma warning restore 1591
