#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using Excelsior.Domain;

namespace Excelsior.Domain	
{
	public partial class WF_StepList
	{
		private long _WFStepListID;
		public virtual long WFStepListID
		{
			get
			{
				return this._WFStepListID;
			}
			set
			{
				this._WFStepListID = value;
			}
		}
		
		private string _WFStepListDes;
		public virtual string WFStepListDes
		{
			get
			{
				return this._WFStepListDes;
			}
			set
			{
				this._WFStepListDes = value;
			}
		}
		
		private int? _SortingOrder;
		public virtual int? SortingOrder
		{
			get
			{
				return this._SortingOrder;
			}
			set
			{
				this._SortingOrder = value;
			}
		}
		
		private IList<WF_TempStep> _WFTempSteps = new List<WF_TempStep>();
		public virtual IList<WF_TempStep> WF_TempSteps
		{
			get
			{
				return this._WFTempSteps;
			}
		}
		
	}
}
#pragma warning restore 1591
