#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using Excelsior.Domain;

namespace Excelsior.Domain	
{
	public partial class WF_Sequence : PACS_Series
	{
		private long? _WFTempStepID;
		public virtual long? WFTempStepID
		{
			get
			{
				return this._WFTempStepID;
			}
			set
			{
				this._WFTempStepID = value;
			}
		}
		
		private long? _CategoryFlagID;
		public virtual long? CategoryFlagID
		{
			get
			{
				return this._CategoryFlagID;
			}
			set
			{
				this._CategoryFlagID = value;
			}
		}
		
		private DateTime? _LastStepCompletionDate;
		public virtual DateTime? LastStepCompletionDate
		{
			get
			{
				return this._LastStepCompletionDate;
			}
			set
			{
				this._LastStepCompletionDate = value;
			}
		}
		
		private long? _AssignedToID;
		public virtual long? AssignedToID
		{
			get
			{
				return this._AssignedToID;
			}
			set
			{
				this._AssignedToID = value;
			}
		}
		
		private WF_TempStep _WFTempStep;
		public virtual WF_TempStep WFTempStep
		{
			get
			{
				return this._WFTempStep;
			}
			set
			{
				this._WFTempStep = value;
			}
		}
		
		private WF_CategoryFlag _WFCategoryFlag;
		public virtual WF_CategoryFlag WFCategoryFlag
		{
			get
			{
				return this._WFCategoryFlag;
			}
			set
			{
				this._WFCategoryFlag = value;
			}
		}
		
		private CONTACT_User _AssignedTo;
		public virtual CONTACT_User AssignedTo
		{
			get
			{
				return this._AssignedTo;
			}
			set
			{
				this._AssignedTo = value;
			}
		}
		
	}
}
#pragma warning restore 1591
