#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using Excelsior.Domain;

namespace Excelsior.Domain	
{
	public partial class WF_Template
	{
		private string _WFTemplateType;
		public virtual string WFTemplateType
		{
			get
			{
				return this._WFTemplateType;
			}
			set
			{
				this._WFTemplateType = value;
			}
		}
		
		private string _WFTemplateNote;
		public virtual string WFTemplateNote
		{
			get
			{
				return this._WFTemplateNote;
			}
			set
			{
				this._WFTemplateNote = value;
			}
		}
		
		private string _WFTemplateName;
		public virtual string WFTemplateName
		{
			get
			{
				return this._WFTemplateName;
			}
			set
			{
				this._WFTemplateName = value;
			}
		}
		
		private long _WFTemplateID;
		public virtual long WFTemplateID
		{
			get
			{
				return this._WFTemplateID;
			}
			set
			{
				this._WFTemplateID = value;
			}
		}
		
		private long? _TrialID;
		public virtual long? TrialID
		{
			get
			{
				return this._TrialID;
			}
			set
			{
				this._TrialID = value;
			}
		}
		
		private bool _IsLocked;
		public virtual bool IsLocked
		{
			get
			{
				return this._IsLocked;
			}
			set
			{
				this._IsLocked = value;
			}
		}

        private bool _IsActive;
        public virtual bool IsActive
        {
            get
            {
                return this._IsActive;
            }
            set
            {
                this._IsActive = value;
            }
        }

        private PACS_Trial _PACSTrial;
		public virtual PACS_Trial PACSTrial
		{
			get
			{
				return this._PACSTrial;
			}
			set
			{
				this._PACSTrial = value;
			}
		}
		
		private IList<WF_TempStep> _WFTempSteps = new List<WF_TempStep>();
		public virtual IList<WF_TempStep> WF_TempSteps
		{
			get
			{
				return this._WFTempSteps;
			}
		}
		
		private IList<PACS_TPProcList> _PACSTPProcLists = new List<PACS_TPProcList>();
		public virtual IList<PACS_TPProcList> PACS_TPProcLists
		{
			get
			{
				return this._PACSTPProcLists;
			}
		}

        private IList<PACS_SeriesGroup> _PACSSeriesGroups = new List<PACS_SeriesGroup>();
        public virtual IList<PACS_SeriesGroup> PACS_SeriesGroups
        {
            get
            {
                return this._PACSSeriesGroups;
            }
        }
    }
}
#pragma warning restore 1591
