#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using Excelsior.Domain;

namespace Excelsior.Domain	
{
	public partial class WF_TempStep
	{
		private long _WFTempStepID;
		public virtual long WFTempStepID
		{
			get
			{
				return this._WFTempStepID;
			}
			set
			{
				this._WFTempStepID = value;
			}
		}
		
		private long? _WFTemplateID;
		public virtual long? WFTemplateID
		{
			get
			{
				return this._WFTemplateID;
			}
			set
			{
				this._WFTemplateID = value;
			}
		}
		
		private int? _WFStepOrder;
		public virtual int? WFStepOrder
		{
			get
			{
				return this._WFStepOrder;
			}
			set
			{
				this._WFStepOrder = value;
			}
		}
		
		private long? _WFStepListID;
		public virtual long? WFStepListID
		{
			get
			{
				return this._WFStepListID;
			}
			set
			{
				this._WFStepListID = value;
			}
		}
		
		private bool _ShouldSkip;
		public virtual bool ShouldSkip
		{
			get
			{
				return this._ShouldSkip;
			}
			set
			{
				this._ShouldSkip = value;
			}
		}
		
		private WF_Template _WFTemplate;
		public virtual WF_Template WFTemplate
		{
			get
			{
				return this._WFTemplate;
			}
			set
			{
				this._WFTemplate = value;
			}
		}
		
		private WF_StepList _WFStepList;
		public virtual WF_StepList WFStepList
		{
			get
			{
				return this._WFStepList;
			}
			set
			{
				this._WFStepList = value;
			}
		}
		
		private IList<WF_Sequence> _WFSequences = new List<WF_Sequence>();
		public virtual IList<WF_Sequence> WF_Sequences
		{
			get
			{
				return this._WFSequences;
			}
		}
		
		//private IList<AUDIT_Record> _AUDITRecords = new List<AUDIT_Record>();
		//public virtual IList<AUDIT_Record> AUDIT_Records
		//{
		//	get
		//	{
		//		return this._AUDITRecords;
		//	}
		//}

        private IList<CRF_Datum> _CRFData = new List<CRF_Datum>();
        public virtual IList<CRF_Datum> CRF_Data
        {
            get
            {
                return this._CRFData;
            }
        }
    }
}
#pragma warning restore 1591
